### ISSUE TITLE
Add generic "Search for selection" action

### ISSUE THREAD

**Issue by mikecrittenden** [mikecrittenden/shortkeys#103]
This should allow the user to enter a URL with a placeholder that will be replaced by selected text, so that pretty much any search engine will be supported. This came about in the comments of #45 (cc @AlexByte).

**Comment by reg2s** [comment]
Hi, Mike,
Thank you for the great extension. Today I saw that it is updated so decided to share some of my code that was overwritten by update.) Excuse me, If this is not the proper place to write this.

To solve this specific task I added the following code to extension's files:

background.js:
```
else if (action === 'javascript-open-bg') {
    chrome.tabs.executeScript( null, {code:request.code}, function(results) { chrome.tabs.create({url:results0],active:false}) });
}
```

options.js:
`{value:'javascript-open-bg', label: 'Run JavaScript and open result in background page', group: 'Other'},
`
options.html:
```
<div ng-show="key.action == 'javascript-open-bg'" class="form-group javascriptconfig">
    <label>Javascript code to run (background.js)</label>
    <textarea ui-codemirror ui-codemirror-opts="editorOptions" rows="20" ng-model="key.code" class="form-control"></textarea>
</div>
```

Script entered on settings page:
```
s = window.getSelection().toString();
if (s != "") {
  s = "https://www.google.com/search?q=" + s;
};
s
```

Using not placeholder but general-purpose script in settings will give more flexibility.

**Comment by mikecrittenden** [comment]
Awesome! Thank you for that!
