### ISSUE TITLE
The "Jump to tab or URL" action opens the target URL twice in Chrome

### ISSUE THREAD

**Issue by xcv58** [mikecrittenden/shortkeys#105]
Chrome version: 63.0.3230.0 (Official Build) dev (64-bit)
Extension version 2.2.2

**Comment by mikecrittenden** [comment]
I'm not able to reproduce this - are you positive that you don't just have duplicate shortcuts set up, and it's triggering both of them?

**Comment by xcv58** [comment]
I can only reproduce on one laptop. Let me check it again.

**Comment by xcv58** [comment]
It's fixed after restart laptop. Thanks!
