### ISSUE TITLE
Add "Tab Title" filter field for the "Jump to tab" action

### ISSUE THREAD

**Issue by CelineTam** [mikecrittenden/shortkeys#106]

**Comment by mikecrittenden** [comment]
This is a fantastic idea and wouldn't be hard to add at all. So in addition to the URL matches text field there would be a Name Matches text field, and a message to only use one or the other, yeah?

**Comment by mikecrittenden** [comment]
Hmm, or actually just keep the 1 field, and you can enter either a tab title (with wildcard) or URL in that field.

**Comment by mikecrittenden** [comment]
#121 fixes this.
