### ISSUE TITLE
Shortcut with "+" recently stopped working consistently

### ISSUE THREAD

**Issue by WDISupport** [mikecrittenden/shortkeys#108]
We use Shortkeys to re-map our number pad "+" key as a Tab (move to the next field) key for quick order entry. We do this by using the following Javascript:
var inputs = Array.prototype.slice.call(document.querySelectorAll("input"))
var index = (inputs.indexOf(document.activeElement)+1) % inputs.length;
inputs[index].focus().select();

This had been working great, but today it no longer works. Can you help with this issue? Thanks!

**Comment by mikecrittenden** [comment]
Hmm, I'm not sure why that might be. Does it work if you switch it to
something besides +? Maybe try something basic like ctrl+a as a simple
test? I'm wondering if it's the + that is failing or the JS itself. I can
say that + works fine form me, in general.

**Comment by WDISupport** [comment]
What version of Chrome are you running? We are currently on  63.0.3239.84. I think it may be a version issue because it used to work fine.

**Comment by mikecrittenden** [comment]
Can I see a screenshot of your setup?

**Comment by WDISupport** [comment]
![image](https://user-images.githubusercontent.com/34452230/33846176-c7bffa4c-de73-11e7-803c-96734bf00bd3.png)

**Comment by mikecrittenden** [comment]
Bizarre - any errors in the JS console of the browser developer tools?

**Comment by mikecrittenden** [comment]
OH, also, try `plus` instead of `+`.

**Comment by WDISupport** [comment]
Where would I see that? Sorry, I’m not a web developer.

Thomas Nugent
Director of IT & Administration
WD Wilsbach Distributors, Inc.
www.wilsbach.com<http://www.wilsbach.com/>
tnugent@wilsbach.com<mailto:tnugent@wilsbach.com>
Phone: (717) 561-3116
Toll Free: 1-866-624-2773  Ext. 229
Fax: (717) 561-2109

**Comment by mikecrittenden** [comment]
@WDISupport first, try `plus` instead of `+` and see if that helps.

**Comment by mikecrittenden** [comment]
Closing this because `plus` (and `+`) seem to be working consistently in general.
