### ISSUE TITLE
Support for Tree Style Tab

### ISSUE THREAD

**Issue by ElhemEnohpi** [mikecrittenden/shortkeys#109]
Since Dorando Keyconfig no longer works in Firefox Quantum, I was hoping to use shortkeys as a replacement, especially for use with Tree Style Tab. There's a [new API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons) for it, but it doesn't seem to work with shortkeys. Is there any possibility to support it?

**Comment by mikecrittenden** [comment]
This is probably a question for @pmalecka who maintains the Firefox fork at https://github.com/pmalecka/chrome-shortkeys

**Comment by ElhemEnohpi** [comment]
Ok, thanks. Fyi, the website for the [Firefox version](https://addons.mozilla.org/en-US/firefox/addon/shortkeys/) says to report issues here. I see now that it's already been reported in pmalecka's repository by several people since October, but he hasn't responded.

**Comment by pmalecka** [comment]
indeed, I had changed the addon info to point here. Mike and I are working on merging the Firefox codebase back to this repo. I figured it makes sense to keep the issues in one place as well.
@mikecrittenden if you are ok with this, of course.


null

**Comment by mikecrittenden** [comment]
Oh great! Never mind then. I'll reopen.

**Comment by ElhemEnohpi** [comment]
Thanks. I'm not a Javascript expert, but it looks to me like the "run Javascript" behaviour runs in the page context, where the Tree Style Tab API won't work. I think you'd need to either add a lot of TST-specific actions to the list of behaviours, or somehow allow customizable Javascript that can control the browser (duplicate tabs and so on). There would also have to be a setup step to initialize communication between shortkeys and TST.

as well as setting up the communication with it. Does that sound right?

**Comment by mikecrittenden** [comment]
Sounds like maybe this needs #76 which I closed because it didn't seem valuable at the time. That would theoretically allow you to run arbitrary JS with access to the browser (or TST) APIs. I suppose I'll close this issue and reopen that one, to investigate how possible that is.

**Comment by ElhemEnohpi** [comment]
If you can't do a general-purpose custom javascript function, would it be possible to support Tree Style Tab with a few built-in behaviours? First, technically speaking, would it work? And second, do you have any interest in that?

For example, because it can be difficult to reposition tabs with the mouse, the main keyboard shortcuts I use are:
- Promote(indent)/demote(unindent) tab
- Move tab up/down

The next most common ones I use are for creating new or duplicate tabs in a particular position:

- New / Duplicate tab as (variations): child, sibling, next sibling, independent, etc.

**Comment by mikecrittenden** [comment]
Yeah I'll take a peek at this.

**Comment by mikecrittenden** [comment]
I just poked around. It's a bit more complex than I have time to build at the moment. I'd be happy to accept PRs for this, but otherwise I'll leave it up to @pmalecka (as the FF maintainer of Shortkeys) whether he's interesting in adding support for this or not.

**Comment by ElhemEnohpi** [comment]
Ok, thanks, I understand. I'll see if I can drum up some ideas/help among the TST users. I think there's about a quarter million of them or so, and they tend to be enthusiastic about it, so I'm sure we can do something. Ideally we'd find a solution for general custom javascript in the background, as it would apply to controlling many other addons, not just TST.

**Comment by mikecrittenden** [comment]
@Lej77 has created a PR that might fix this: https://github.com/mikecrittenden/shortkeys/pull/149

**Comment by mikecrittenden** [comment]
I'm going to close this issue because now that #76 is reopened, that will be the path forward for supporting this.
