### ISSUE TITLE
Emphasize + on "Example: ctrl+b"

### ISSUE THREAD

**Issue by olafdietsche** [mikecrittenden/shortkeys#110]
It took quite a while to figure out, why shortkeys wasn't working as I expect.

I tried several different ctrl-combinations, until I stumbled upon my mistake of using "ctrl-b" instead of "ctrl+b". Somehow it should be highlighted, that "ctrl-" doesn't work, and "ctrl+" is the proper way to define a shortcut. At least, there should be a note in the "FAQs and Troubleshooting" page or on the help page.

**Comment by mikecrittenden** [comment]
Did you see this page, which is linked to right above the "Keyboard shortcut" text input? https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#supported-keyboard-shortcuts

**Comment by olafdietsche** [comment]
Yes, I saw this page. But even then, I didn't realize what I was doing wrong, because `ctrl-b` seemed natural to me.

This is why I think, it would be good to highlight, that it must be plus and not minus, maybe

*Note that `-` (`ctrl-b`) does not work for joining keys`*

or some similar notice.

**Comment by mikecrittenden** [comment]
Do you think this will suffice? https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys/_compare/2dc7f9f5b026a6b15eadebe35743c5e09e2b39d3...154b8bac5dfe2e5dfb771d5907c198c1920d18c7

Feel free to reopen if not. Thank you!

**Comment by olafdietsche** [comment]
This looks very good, thank you.
