### ISSUE TITLE
Integrate functionality of "Cycle Input Focus Plus" extension

### ISSUE THREAD

**Issue by thenlich** [mikecrittenden/shortkeys#112]
I'm the author of the Firefox extension "Cycle Input Focus Plus" (https://addons.mozilla.org/en-US/firefox/addon/cycle-input-focus-plus/). This provides 4 shortcuts to navigate pages with text and password fields.

I would like to contribute this functions to "shortkeys" since this would eliminate much duplicate code. Would you support this code merge? (I could continue to support the added code of course)

**Comment by mikecrittenden** [comment]
Sure! I'd definitely be in favor of merging and adding this functionality
to Shortkeys.
