### ISSUE TITLE
Issue with Shortkeys 2.2.6

### ISSUE THREAD

**Issue by owensgithub** [mikecrittenden/shortkeys#113]
I'm not sure if this is happening to anyone else, but there seems to be an issue with Shortkeys saving shortcuts in 2.2.6. The only workaround I've found is if I click on 'Save' and then refresh a tab, shortcuts will start working again. Although, if I restart Firefox they'll stop working. I have to go through the same process of 'Save' and refresh to get them working again. Any ideas?

**Comment by pmalecka** [comment]
Super weird, I am actually not experiencing this issue on my side.
Are you logged in to Firefox with an account? Do you have sync enabled?
Do you have your history setup so that no browsing history is saved?

**Comment by owensgithub** [comment]
Hi. Yeah logged into my Firefox account with sync enabled and have bookmarks, add-ons and preferences synced. I have history disabled. It seems to be only saving settings temporarily when I click 'Save' and then clearing them once I restart Firefox. Maybe it's a modified preference causing the issue?

**Comment by pmalecka** [comment]
Okay, so a fix is underway. @mikecrittenden can we also increase the version to 2.2.7?

**Comment by mikecrittenden** [comment]
@pmalecka yeah https://github.com/mikecrittenden/shortkeys/releases/tag/v2.2.7 is available now. Thank you!

**Comment by owensgithub** [comment]
Thanks! Everything's working great now in 2.2.7

**Comment by mikecrittenden** [comment]
@pmalecka oops I misunderstood your request. 2.2.7 is unrelated to this but not a critical release for FF anyway. Let's get this change merged everywhere for 2.2.8 so that they're back in sync.

**Comment by pmalecka** [comment]
@mikecrittenden I see, so
the 2.2.7 you've built:  https://github.com/mikecrittenden/shortkeys/releases/tag/v2.2.7 - will be a bit different from 2.2.7 that I pushed to AMO (that one contains the critical fix). In 2.2.8 we could try and align the storage for all browsers.
