### ISSUE TITLE
Java script stopped working

### ISSUE THREAD

**Issue by Patuta** [mikecrittenden/shortkeys#116]
I have no expertise in Java. All I did was to add a new item in ShortKeys, choose "Run JavaScript" as behaviour, select a keyboard shortcut and copy some Java script into "Javascript code to run". 
It worked like a charm until todays update. No it has fallen silent. Any idea what's going wrong?
Here's the script:

javascript:s=window.getSelection();if(!s||s==''){for(i=0;i<frames.length;i++){s=frames[i].window.getSelection();if(s&&s!='')break;}}if(!s||s=='')void(s=prompt('Mark or fill in expression first:',''));if(s&&s!=''){dw=window.open('http://www.dict.cc/?bm=1&s='+escape(s),'dict','width=1100,height=500,resizable=yes,scrollbars=yes');dw.focus();}][chrome://browser/content/browser.xul");

**Comment by mikecrittenden** [comment]
v2.2.6 was corrupted for everyone - v2.2.7 is available now. To speed up the update, go to chrome://extensions and click "Developer mode" then click "Update extensions now"

(#115 is related)
