### ISSUE TITLE
After update of reinstall REMOVED ALL BOOKMARKS, History, passwords

### ISSUE THREAD

**Issue by bonor11** [mikecrittenden/shortkeys#118]
![clipboard02](https://user-images.githubusercontent.com/6589814/34083381-5f6caf10-e370-11e7-8aa8-ca60b4d03ebf.jpg)

## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1. Clean install
2. See attachment
3. After confirm, IT REMOVED EVERYTHING! Bookmarks to passwords etc!!!!
4.

**Comment by mikecrittenden** [comment]
@pmalecka do you think this is possible in the FF version? Seems unrelated to Shortkeys. I don't think it even has permission to delete passwords, for example.

**Comment by bonor11** [comment]
No Idea but I believe what you're saying! 
It looks like FF also installed an update today...could be related.
Either way, something really mest up everything. I just discoverd a folder on my desktop "Oude Firefox-gegevens" (old FF data) which I never had before after an update.. strange....

**Comment by pmalecka** [comment]
I think it should not be, nowhere in the code do we actually delete that stuff (apart from the clear downloads action). I was hoping we would get some more details on the issue there, it originally came as a review ob AMO. I'll try and replicate this tomorrow.@bonor11 can you replicate this on a fresh FF profile? What is your FF version? Did it also remove other addons?
null

**Comment by bonor11** [comment]
57.0.2 (64-bits)
Yes all add-one are gone (luckely for me I use the sync feature)

After sync I had everything restored. Then I reistalled Shortkeys and it was installed without erasing stuff. I am starting to think the problem is indeed not related to Shortkeys but to an FF update (No idea!)

Please remove my bad review and close this thread it you can.
