### ISSUE TITLE
Jump to a specific tab by number/index

### ISSUE THREAD

**Issue by pileon** [mikecrittenden/shortkeys#119]
I often use special keys to go to a specific tab using one of the digit keys. Like `1` being the first tab, `2` for the second, etc., until `9` which is always the last tab.

I think it might be a good idea to implement this feature, instead of matching a specific URL.

This is (IMO) important for the Firefox plugin in Linux, since it doesn't use `ctrl+<digit>` like it used to, which have become part of my cross-platform workflow when browsing.

**Comment by mikecrittenden** [comment]
Agreed - this would be a useful feature. It could probably include a number field to select which tab.

**Comment by p3lim** [comment]
Would love support for this, I'm moving constantly between Windows and Linux, and the default keybindings for this differ between them (Ctrl+1 on Windows, Alt+1 on Linux does the same thing).

**Comment by mikecrittenden** [comment]
#121 fixes this.
