### ISSUE TITLE
windows key modifier

### ISSUE THREAD

**Issue by zalmoxis** [mikecrittenden/shortkeys#120]
what exactly is the windows key modifier supposed to be? I tried all the available options and none seem to work... I am on debian stable

## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Try `meta` - see more info here: https://github.com/ccampbell/mousetrap/issues/81
