### ISSUE TITLE
Shortcuts don't work when search box (ctrl+f) is open

### ISSUE THREAD

**Issue by yennor** [mikecrittenden/shortkeys#122]
I've got shortcuts for f1 and f2, which will switch to the previous and next tab respectively.ut
This works mostly.
But when pressing ctrl-f to search for something then afterwards the shortcuts don't work anymore. I need to press escape first, to close the search box, and then the shortcuts work again

**Comment by mikecrittenden** [comment]
Unfortunately there's nothing we can do about that in most cases - Chrome doesn't allow it. 

Note that if you're using Chrome then you CAN use the built in Chrome Keyboard Shortcuts UI to edit some (not all) Shortkeys shortcuts, and doing so will allow them to run when you have the find box open, but there are some limitations to that approach (such as the fact that you HAVE to use ctrl or alt in your shortcut so f1 and f2 won't work). See this for more info: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#Do_I_use_Chromes_Keyboard_Shortcuts_settings_or_the_Shortkeys_options_page

**Comment by yennor** [comment]
actually I was talking about Firefox (I wasn't aware of that that extension also works in chrome).
But in that case I guess it has the same restrictions?

**Comment by mikecrittenden** [comment]
Sadly no, Firefox doesn't have a built in UI for shortcuts like Chrome does, so there's nothing we can do there. Unfortunately you're out of luck at the moment on Firefox.
