### ISSUE TITLE
Shortcut actions work multiple times

### ISSUE THREAD

**Issue by bdanylenko** [mikecrittenden/shortkeys#123]
Shortkeys add-on installed, key bindings are set. I've set 'command+shift+[' for previous tab and 'command+shift+]' for next tab. It works perfectly if all of tabs is an empty(with no sites opened). When tabs loaded with sites, for example  github.com and nodejs.org it works two times instead of one, i.e. it switched two tabs.
There are no js errors in console.

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 57.0.3 ( 64 bit )
* Operating System and version: mac OS High Sierra 10.13.2

**Comment by mikecrittenden** [comment]
I hate to ask the dumb question, but are you positive that you don't have duplicate shortcuts set up? Like one on the Shortkeys UI and another in the Chrome Keyboard Shortcuts UI? If that isn't the case, then dosanle Shortkeys and see if those shortcuts still work.

**Comment by mikecrittenden** [comment]
I'm going to close this for lack of info but feel free to reopen!
