### ISSUE TITLE
unable to set keyboard shortcuts using Ctrl and Cmd keys on Firefox 

### ISSUE THREAD

**Issue by WilDieteren** [mikecrittenden/shortkeys#124]
L.S.,

I have just discovered shortkeys today, and I am trying to set keyboard shortcuts using the Ctrl and Cmd keys to reproduce keyboard shortcuts set through the legacy "customizable shortcuts" extension. I am regretfully unable to get it to work: typing either Ctrl or Cmd plus an additional key does not seem to do anything. Not sure whether this is a limitation of shortkeys or whether I am doing something wrong.

I am using Firefox 58b13 and shortkeys 2.2.7 on macOS 10.13.2. Hope I am just doing something wrong, and someone can explain what.

Wil Dieteren

**Comment by mikecrittenden** [comment]
If I understand you correctly, then the problem is that you actually have to type out the keyboard combination letter by letter instead of just hitting it. So actually type out "ctrl+r" or whatever it is Instead of hitting ctrl+r with the text box focused.

**Comment by WilDieteren** [comment]
@mikecrittenden,

No, typing the Ctrl key followed by the arrow up key for example does nothing, i.e. nothing shows in the text box. Have not tried typing out the keyboard combination, would that work?

Wil Dieteren

**Comment by mikecrittenden** [comment]
Yes, I'm saying you have to actually type out c then t then r then l, etc.

**Comment by WilDieteren** [comment]
@mikecrittenden,

OK, misunderstood your earlier reply, thanks for the help. Another question, is it possible to overrule the default Firefox keyboard shortcuts through shortkeys?

Wil Dieteren

**Comment by mikecrittenden** [comment]
I'm a Chrome user myself (Shortkeys works for both) but I believe Firefox allows you to override some shortcuts and not others. Give it a shot for whichever ones you have in mind and see. @pmalecka may have more insight, as the maintainer of the FF version?

**Comment by WilDieteren** [comment]
@pmalecka,

Is it possible to overrule the default Firefox keyboard shortcuts through shortkeys?

Wil Dieteren

**Comment by WilDieteren** [comment]
@pmalecka,

Forget about my previous question, I have found that it is possible to overrule the default Firefox keyboard shortcuts.

Wil Dieteren
