### ISSUE TITLE
chnage shortcut for reader mode and set shortcut for "list all tabs" 

### ISSUE THREAD

**Issue by WilDieteren** [mikecrittenden/shortkeys#126]
L.S.,

Would it be possible to have an option to change the shortcut for reader mode, and have the option to set a shortcut for "list all tabs", both for Firefox 57 on macOS?

Wil Dieteren

**Comment by mikecrittenden** [comment]
@WilDieteren can you explain what "List all tabs" does? Maybe @pmalecka will have some insight into whether it's possible to change the shortcut for Reader mode - as far as I know that's not allowed via the webextension API though.

**Comment by WilDieteren** [comment]
@mikecrittenden,

"List all tabs" opens a drop down window containing a list of all the tabs opened in Firefox in the currently focussed window. It is invoked by clicking the ∨ symbol at the utmost right of the tab bar. I made some screenshots but seem to be unable to add them. Hope the explanation above clarifies what I mean.

Wil Dieteren

**Comment by mikecrittenden** [comment]
Gotcha - that makes sense. Unfortunately right now it looks like the Firefox webextension API doesn't allow triggering either of these things, so I'm going to close this for now. Hopefully as the API develops and gets extended, they'll add support for these in FF.
