### ISSUE TITLE
Add Copy & Paste behavior ?

### ISSUE THREAD

**Issue by cheezystix** [mikecrittenden/shortkeys#127]
Recently my SHIFT-INSERT in Chrome no longer works.
Since I have been using this for some 25+ years it's a hard habit to break
Wanted to map a custom keyboard mapping to mimic this in the extension
But it's not available as a behavior in the extension (paste that is)

## Your Environment
Windows 10
Chrome (latest)

## Expected Behavior
Would like to setup a custom keyboard shortcut for SHIFT-Insert to equal PASTE (or CNTRL-V)

## Current Behavior
SHIFT-INSERT no longer works for me in Chrome

**Comment by mikecrittenden** [comment]
See #33. I decided not to add support for this since copy/paste is an OS-wide operation (rather than a browser one) and there are better tools for that already, as mentioned in that issue.
