### ISSUE TITLE
Catching operating system level shortcuts

### ISSUE THREAD

**Issue by xavsimon** [mikecrittenden/shortkeys#128]
Hi Mike,

Thanks for the great extension - loving it.
I am trying to find a way to catch what I believe are operating system shortcuts (and I am not an expert developer by any stretch of the imagination, so this may or may not make sense...). I found that, for example, I can catch Alt-F4 when I am on full screen (testing on chrome), but not in any other state of the window.
I cannot, however, use other shortcuts such as alt-tab or the windows key by itself in any state of the window to create a custom shortcut. I suspect this is because this is handled by the operating system before it gets to Chrome, but am wondering if there is a way to tweak it?

I realize this may sound like a stupid thing to try and achieve, but there is actually a really good reason behind it for a project I am working on...

thanks in advance
Kind regards
Xavier Simon

**Comment by mikecrittenden** [comment]
Seems like you may be looking for something like https://autohotkey.com/ rather than Shortkeys. Shortkeys is a little too low in the OS-level stack to catch things that already have bindings for them.
