### ISSUE TITLE
Can't disable ctrl+q (or anything else AFAICT)

### ISSUE THREAD

**Issue by jun0** [mikecrittenden/shortkeys#129]
I can't seem to disable ctrl+q with shortkeys.  In fact, shortkeys doesn't seem to be doing anything at all.  I hope I'm just missing something, because this would be very useful if it works...

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 58.0b14 for Ubuntu
* Operating System and version: Ubuntu GNU/Linux 17.04, amd64

## Expected Behavior

Ctrl+q should not quit the browser; the shortcut should be disabled. 

## Current Behavior

Ctrl+q just keeps quitting the browser no matter what I do in shortkeys' settings.

## Steps to Reproduce (for bugs)

1. Install shortkeys from `about:addons`.  Restart browser.
2. Add a shortcut entry, set "Keyboard shortcut" to "ctrl+q" (without quotes) and "Behavior" to "Do nothing".  Restart browser.
3. Open a webpage, say `google.com`.
4. Type ctrl+q.  The browser should now ignore the keys, yet it performs the original function of quitting the browser.

Variations I've tried on this procedure (none of which made any difference):
* I've tried disabling ctrl+n, disabling ctrl+w, and setting ctrl+w to zoom in, instead of trying to disable ctrl+q.
* I've tried opening "Activation settings" and checking "Active while in form fields" and setting "Websites" to "all sites".
* I've tried this on `google.com` while the focus is on the textbox and while the focus is out of the textbox.
* I've tried upgrading my firefox from 58.0b7 to 58.0b14.

Any ideas what might be wrong?

**Comment by mikecrittenden** [comment]
Thanks for the awesome bug report and all the details. I'm going to use this as an example from now on! 👍 

Sadly overriding ctrl+q (or any of the other shortcuts you listed) isn't something that Shortkeys is able to do. There are some core browser shortcuts that the extension API doesn't have the ability to override. Note that there used to be lots of FF addons for this, but none of them work anymore now that the old addon API has been removed and the webextension API can't do it (you probably already knew that). Sorry about that. If/when Firefox gives more control then Shortkeys will definitely support that.

**Comment by onebod** [comment]
Installed in Firefox.
It says I can use it to "disable browser shortcut", but
it doesn't work on ctrl+w.

I tried to post a review, but the Add a Review button within Firefox 
(about:addons > Shortkeys > Options)
links to Chrome.Google.com/webstore.

All I want to do is disable ctrl+w
It should tell me if it can't do it without me hunting down this post.
I presume I'd be correct is saying Shortkeys cannot disable ctrl+w?

James

**Comment by mehturt** [comment]
Same as @onebod  I can't disable ctrl+w, is that not supported? I guess the extension should recognize keys that cannot be modified and report that when user is trying to assign action to it.
