### ISSUE TITLE
Add actions for editing the current URL

### ISSUE THREAD

**Issue by ncoleman** [mikecrittenden/shortkeys#131]
Debian Linux, Chromium

It would be useful to have the ability to edit the URL, and even better with regex search-replace.

- I frequently use the 'g u' shortcut (from cVim & Vimium) to "go up" an element in the URL path, e.g. remove the last element in the path.  

- Another quick-but-good shortcut is to remove all path elements from the URL and go straight to the root domain.  

- Another use case is to edit Google's time parameters in its search requests.  For example, "within a year" is '&tbs=qdr:**y**', and "within 2 years" is '&tbs=qdr:**y2**'.  It is very useful to be able to use a shortcut to amend an existing search by appending '2' (or 3 or 4; or m6 for six months, and so on) to the appropriate parameter string.  

(FYI for the reader, there are dozens of Google parameters, ranging from within time, within date, image size, image colour, country, and more.  Once you have URL editing or custom searches, they are available easily and quickly.)

**Comment by mikecrittenden** [comment]
Just a note that this should be possible with the Run JS action, if you know how to write some basic JS. But I'm leaving this open because I think these would be useful actions to support in general.
