### ISSUE TITLE
command+§ not working on Mac

### ISSUE THREAD

**Issue by essesset** [mikecrittenden/shortkeys#132]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox Quantum 57.0.1 (64-bit)
* Operating System and version: Mac OS X Yosemite 10.10.5

## Expected Behavior
Tried the combination command+§ for Go Back, which does not work. Other combinations such as command+< or command+1 works well. This combination has worked with pre-Quantum Firefox with another similar add-on, however not to my knowledge with your add-on. It would be a great combination to have working (and slightly strange that it isn't?)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
So this is probably an issue that belongs to https://github.com/ccampbell/mousetrap/ since that's the keyboard shortcut lib Shortkeys is using. Feel free to create an issue there - ccampbell is usually really responsive and helpful.
