### ISSUE TITLE
Provide support to toggle Add-ons in Firefox

### ISSUE THREAD

**Issue by grahamarmfield** [mikecrittenden/shortkeys#133]
The add-on is great for triggering all kinds of activity in Firefox with custom shortcodes. But I can't find a way to trigger Firefox add-ons in your documentation. Is it possible? If not, could it be possible?

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 57
* Operating System and version: Windows 10 - Fall Creators

**Comment by mikecrittenden** [comment]
Unfortunately the Firefox API doesn't currently allow for one extension to toggle the enabled/disabled status of another.

**Comment by grahamarmfield** [comment]
OK, thanks for letting me know.


Regards
Graham Armfield
