### ISSUE TITLE
Shortcut didnt work when mouse is focused in text input

### ISSUE THREAD

**Issue by xuanlinh91** [mikecrittenden/shortkeys#134]
I haved add shortcut to turn to next tab or previous tab in chrome.
While scrolling to next tab or previous tab, if current tab has text input (like account input or search input) and it's has auto focus. Then my shortcut does not work

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome 63.0.3239.132 (lastest)
* Operating System and version: Windows 10 64bit

## Steps to Reproduce (for bugs)

1.
Import my current setting shortcut 
[{"action":"nexttab","blacklist":false,"exported":true,"key":"Alt+right","open":false,"sites":"*mail.google.com*","sitesArray":["*mail.google.com*"]},{"action":"prevtab","blacklist":false,"exported":true,"key":"Alt+left","open":false,"sites":"*mail.google.com*","sitesArray":["*mail.google.com*"]},{"action":"firsttab","blacklist":false,"exported":true,"key":"Alt+home","open":false,"sites":"*mail.google.com*","sitesArray":["*mail.google.com*"]},{"action":"lasttab","blacklist":false,"exported":true,"key":"Alt+end","open":false,"sites":"*mail.google.com*","sitesArray":["*mail.google.com*"]}]

2. Restart Chome
3.Open three tab: github.com, google.com, amazon.com
4. Try to use shortcut: Alt+left, Alt+right to scroll to next tab of previous tab
5. At google.com, mouse is auto focus to search textbox, and the shortcut does not work, it is behaved like default key

**Comment by mikecrittenden** [comment]
See https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#triggering-shortcuts-while-typing-in-form-fields which should solve this for you.
