### ISSUE TITLE
Feature request: paste predefined text string

### ISSUE THREAD

**Issue by SeeSpotRun** [mikecrittenden/shortkeys#135]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Chrome 63.0.3239.132 (Official Build) (64-bit)
* Operating System and version: Arch Linux

## Expected Behavior
I'd like to be able to have a shortcut key paste a predefined text string into the current text edit box.  For example a markdown template for a url link: `[Link text](https://some.url.com "Hover text")`

## Current Behavior
Forgive me if I've missed it but I can't see any such option

**Comment by mikecrittenden** [comment]
Good idea, but for now I've decided to not support this. See #85 for reasoning.

**Comment by SeeSpotRun** [comment]
Thanks, good response

**Comment by jeromelbl** [comment]
Late to the game here, but I was looking for the same thing. You can achieve it in ShortKeys using the Run Javascript behavior with the following code:
```javascript
document.execCommand("insertText", false, "some text here");
```
