### ISSUE TITLE
Add "Close current tab and switch to left/right tab" actions

### ISSUE THREAD

**Issue by zoidbergthepopularone** [mikecrittenden/shortkeys#136]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Firefox 58.0.0
* Operating System and version: Windows 10

## Expected Behavior
I am trying to create a shortcut which would replicate the standard "switch to the next tab" (behavior: Nex Tab) using javascript (behavior: Run Javascript). As far as I can tell, it should look like this:

chrome.tabs.query(
  {currentWindow: true},
  function(tabsInCurrentWindow){
    if (tabsInCurrentWindow.length>1) {
      chrome.tabs.query(
        {currentWindow: true, active: true},
        function(activeTabsInCurrentWindow){
          var currentTab = activeTabsInCurrentWindow[0];
          var wantedTab = tabsInCurrentWindow[(currentTab.index+1+tabsInCurrentWindow.length)%tabsInCurrentWindow.length];
          chrome.tabs.update(wantedTab.id, {active: true});
        }
      )
    }
  }
);

However, the browser complains right at the first line that "chrome" is not defined. Which can be confirmed by putting an alert(chrome) at the start of the code. Based on some searches I did, I tried to replace "chrome" with "browser", and I also tried unqualified "tabs" - but no success, in both cases I am getting a "not defined" error. What am I doing wrong? Is it possibly the case that chrome/browser/tabs are only accessible to an extension but not to the injected code? In that case, is there another solution than either writing my own extension or begging you for inclusion of the behaviors I need (see below)  into Shortkeys?

(The reason why I don't want to use the provided "Next Tab" behavior is that once I get it to run, I want to extend the script to "Close current tab and switch to the next tab" and "Close current tab and close to the previous tab".)

**Comment by mikecrittenden** [comment]
Yeah, unfortunately the "Run Javascript" action runs the JS in the context of the page, which means that it does not have access to browser API commands such as `chrome.tabs.update()`. We've looked at support that here: #76 but (as you can see in the comments there) it's not as simple as you may think. 

So in the meantime, it sounds like you'd just like to have a "Switch to next tab and close current tab" command? That seems useful. I'm not sure what the use case for "Close current tab and close to the previous tab" is though - could you elaborate on that one?

**Comment by zoidbergthepopularone** [comment]
Thanks for the answer.

Perhaps my wording wasn't precise enough - "next" and "previous" can mean several different things. What I specifically need is a "close and select tab to the immediate left" and "close and select tab to the immediate right". The reason for that is very simple: In my workflow, I keep opening new tabs to the right of the current tab. That means that the "left" tab usually refers to "the originator of current tab" (and I want to go there once I determined that I completed reading all the necessary detail and can continue with the broader picture) and "right" tab is either "even more detail from here" or "detail from some page on the left" (and I need to modify my action based on which it is).

**Comment by mikecrittenden** [comment]
I think the current "close tab" should basically do the same thing as "close and select tab to the immediate right" - yeah?

If that's true, then we could just add a "Close current tab and switch to previous tab" action to handle the left, yes?

**Comment by zoidbergthepopularone** [comment]
Pretty much, yes. Until Firefox decides to change the default "Close" behavior (to e.g. "close current tab and select the most current tab in activation order"). That's why I would prefer an explicit "Close tab and select tab to the right" as well. But for the time being, the modification you propose would suffice.

**Comment by mikecrittenden** [comment]
Oh right, I forgot you're using Firefox. Chrome behaves a little differently with that I think. 

Ok, so we need two new actions here. I'll update this issue to reflect that.

**Comment by mikecrittenden** [comment]
Closing some old tasks, feel free to comment if this is still an issue.
