### ISSUE TITLE
Please add Shortcut for "Email link...", probably Ctrl+E keyboard shortcut

### ISSUE THREAD

**Issue by mnba** [mikecrittenden/shortkeys#137]
Please add Shortcut for "Email link...", probably Ctrl+E keyboard shortcut

## Current Behavior
Currently it is absent from selection options

Using Firefox

**Comment by mikecrittenden** [comment]
From what I can tell, there's no extension API yet for this in Firefox, so it's not something that Shortkeys could support. Happy to reopen this if and when that API is added!
