### ISSUE TITLE
Copy default Cmd+C shortcut not working in Firefox when the extension is enabled

### ISSUE THREAD

**Issue by certainlyakey** [mikecrittenden/shortkeys#139]
I'm on a Mac/Firefox combination, and default Cmd+C shortcut stops doing anything when the extension is enabled.

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 57.0.4
* Operating System and version: OS X El Capitan

## Expected Behavior

Cmd+C doesn't work. Copying via context menu or the Edit menu works.

Cmd+C should start working again.

## Current Behavior

Copying with the standard shortcut doesn't copy anything and leaves the previous thing copied in memory. As soon as I disable the extension — it starts working. Removing all the shortcuts doesn't help.
## Steps to Reproduce (for bugs)

1. Enable the extension
2. Try to copy anything with Cmd+C
3. Nothing gets copied

**Comment by mikecrittenden** [comment]
Well that is super bizarre. This is not normal behavior and so far I'm unable to reproduce.

@pmalecka you have any ideas?

**Comment by pmalecka** [comment]
No clue, @certainlyakey is your shortkeys configuration empty? Can you replicate this issue on an empty firefox profile/dev. edition profile?

**Comment by certainlyakey** [comment]
Hmm, the copy shortcut does work on a clean profile. I'll investigate more. Maybe there's a clash with another extension? I use a browser profile upgraded from the old-style Firefox.

**Comment by pmalecka** [comment]
It might be worth trying to wipe the extension config and re-initialize (I'm thinking the extensinon update might have caused an issue with the config).
