### ISSUE TITLE
How to change ctrl+f4 function

### ISSUE THREAD

**Issue by Greyfox210** [mikecrittenden/shortkeys#140]
* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome 63.0.3239.132
* Operating System and version: Windows 1709

Binding ctrl+f4 to "do nothing" does not stop it from closing the tab I'm currently on.
If I try to bind ctrl+f4 to a different function, it does not perform that function, and still closes the tab.

**Comment by mikecrittenden** [comment]
Unfortunately there are some browser shortcuts that just can't be overridden - the browser doesn't allow it. Sadly there's nothing Shortkeys can do here.
