### ISSUE TITLE
Ability to sort shortkeys

### ISSUE THREAD

**Issue by wnickeson** [mikecrittenden/shortkeys#142]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 57.0
* Operating System and version: Windows 7 Pro

## Expected Behavior

I suggest the ability to sort shortkeys by keystrokes (modifier and modified keys), label, perhaps action?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by sterbalr** [comment]
For the default actions, would it make sense to add the list to one or more wiki pages and just put a link out? https://github.com/mikecrittenden/shortkeys/wiki/Windows-Shortcut-keys

**Comment by wnickeson** [comment]
I was thinking about being able to sort my own assigned keys, so as to be able to easily see which ones are still free to be assigned, or to remind me which web page I’ve put on which key (this is primarily what I use this extension for). If sorting is not possible, how about being able to drag each shortcut box manually to a desired position?

*****************************************
  Walter F. Nickeson, Catalog &
    Metadata Management Librarian
  Rush Rhees Library
  University of Rochester
  Rochester, NY  14627-0055
  wnickeson@library.rochester.edu
  (585) 273-2326  fax: (585) 273-1032
*****************************************

**Comment by ThePieMonster** [comment]
I was thinking more along the lines of a option to "disable all" shortcuts on specific sites instead of going to advanced config in each shortcut and specifying a site.

**Comment by mikecrittenden** [comment]
No plans to implement this as it seems like something the vast majority of users wouldn't need, but I'd definitely review a PR if anyone is interested.
