### ISSUE TITLE
Additional Tab Switching Actions — Feature Enhancement Proposal (FF Quantum)

### ISSUE THREAD

**Issue by auralarch** [mikecrittenden/shortkeys#145]
_One of my favorite features and short cuts in Firefox was stripped away with an incompatible plugin in Quantum._    That was:

**SWITCH back to the MOST RECENTly active TAB**

I would like very much for this functionality to be restored if possible.  I had grown more dependent on this than I realized.

I use TreeStyle Tabs and often find that I need to alternate between two tabs a handful of times.  But these tabs are not adjacent or even near each other, nor are they the first or last tab.
I learned that I could locate and click to activate the second tab, and then use the shortcut to switch the next several times to save time and avoid distractions.  In most cases I am copying to combine snippets of text; so keeping the hands on the keyboard is highly preferred.

Another very helpful feature would be **to "MARK"/"Flag" an active TAB with a shortcut.  Then** after marking a tab, be able to **SWITCH back to the MARKED TAB with another shortcut** for the remainder of the session or until marking another tab.

_Are either of these behaviors/actions possible/feasible in the new Firefox Quantum? extensions API?_

_Would anyone else find these features useful?  Or does anyone have any thoughts, ideas, comments or criticisms they would like to share?_

Thank you so much for your attention and consideration!  And for providing this very helpful add-on!

* Shortkeys version: Current
* Browser name and version:  Firefox Quantum 57.0.4 (x64)
* Operating System and version:  Windows 7 Ultimate (x64) and MacOS 10.10.5

**Comment by mikecrittenden** [comment]
Sadly the extensions API doesn't allow this. See #97 for some background info. 

That said, Firefox itself still supports this - have you seen https://alexyv.wordpress.com/2014/01/09/firefox-switching-between-tabs-in-mru-order/ ? That still works in the latest version.
