### ISSUE TITLE
Option To Disable Shortcut Keys On Certain Domains

### ISSUE THREAD

**Issue by ThePieMonster** [mikecrittenden/shortkeys#150]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome
* Operating System and version: Windows 10

## Current Behavior

Suggest adding a option / list to disable this extension on certain websites. Give a table to enter URLs into and the shortcut keys will not function when visiting those domains.

**Comment by mikecrittenden** [comment]
This already exists. See https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#enabling-or-disabling-shortcuts-on-specific-websites

**Comment by ThePieMonster** [comment]
I was thinking more along the lines of a option to "disable all" shortcuts on specific sites instead of going to advanced config in each shortcut and specifying a site.

**Comment by knoajp** [comment]
@ThePieMonster
Yes!! I don't want to repeat expanding all 30 lovely shortcuts to paste the same domains.
