### ISSUE TITLE
i just want my arrow keys to work as page forward or backward keys but it is not working.

### ISSUE THREAD

**Issue by azharalam36** [mikecrittenden/shortkeys#151]
## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.after clicking on new keyboard shortcut no matter how many times i click on arrow keys
2. it won't show any key inserted
3.
4.

**Comment by mikecrittenden** [comment]
You have to actually type the name of the key. So instead of hitting the down arrow, for example, actually type the word `down` into the text box.

**Comment by azharalam36** [comment]
thanks bro now thats working write this thing on extension page on chrome
extension site. thanks again.
