### ISSUE TITLE
Ctrl+j only appears to work for the default of opening downloads

### ISSUE THREAD

**Issue by bryanl-csi** [mikecrittenden/shortkeys#152]
Windows 10
Chrome
Current version of the extension

Tried setting up "ctrl+j" to open a bookmark in a new tab. However it appears this is a  reserved shortcut and I can't use it. Then I tried using "ctrl+space j", also doesn't work. I also tried replacing the word space with an actual space "ctrl+  j".

I'll try some other ctrl+ character/key. I've been using ctrl+<space>+j for so many years via a firefox addon, it's going to be tough to break the habit.

With the firefox addon "Site Launcher", ctrl+space activated the addon, then the next key you pressed would do the function you setup. So the mechanics were a bit different. Also, older ff didn't have an issue opening from a blank tab whereas chrome/ff quantum appears to have issues using a blank tab for things related to extensions, which is mildly annoying in and of itself.

**Comment by mikecrittenden** [comment]
Yeah, `ctrl+j` is reserved like you said. `ctrl+space j` should have worked though, and I just tested and that works for me. Meaning that you hit ctrl+space at the same time, then release both keys, then hit the `j` key. Is that what you're doing?

**Comment by bryanl-csi** [comment]
"ctrl+space j" did work. I must have either been on a form field or held the ctrl key down out of habit.

Thanks!
