### ISSUE TITLE
Add a "Sync to other devices?" per-shortcut checkbox

### ISSUE THREAD

**Issue by vanniktech** [mikecrittenden/shortkeys#153]
Thanks for this cool plugin. I have some shortcuts which would only apply to my Ubuntu machines since I've changed my `Alt` + `Ctrl` keys and hence it would be cool if there are some OS specific keys that will only be allowed on Ubuntu machines and not on Mac OS.

What do you think?

**Comment by mikecrittenden** [comment]
What about maybe having a "Sync to other devices?" checkbox on each shortcut? Would that be just as good for you?

**Comment by vanniktech** [comment]
Yes it would.

**Comment by vanniktech** [comment]
I might be able to contribute this. Can you give me some starter points?

1. I guess we'll just put a checkbox that's enabled by default that says `Sync to other devices` in the options? If so I guess `options.html` is the place for that.

2. Have a new key / value that is `"sync_to_other_devices": false` that can be exported and once the new shortcut is saved it'll either be synced across the Google Chrome persistence layer or not. Where's that code?

**Comment by mikecrittenden** [comment]
@vanniktech yep, options.html - I believe there are already some examples of checkboxes in there. Then you'd want to do some fiddling around with this section: https://github.com/mikecrittenden/shortkeys/blob/master/app/scripts/options.js#L237 to only sync the ones with that checkbox selected.

**Comment by vanniktech** [comment]
Alright cool, I'll get started implementing this in the next few days.
