### ISSUE TITLE
With many shortcuts, the settings list is too long and scrolling doesn't work

### ISSUE THREAD

**Issue by e-rakovets32** [mikecrittenden/shortkeys#154]
http://joxi.ru/82Q7MG1I1LVP6r.jpg

**Comment by mikecrittenden** [comment]
Oof, that's a problem.

**Comment by e-rakovets32** [comment]
@mikecrittenden Please, let me know. Is it bug is fixed?

**Comment by cathairnowhere** [comment]
This is still an issue for me aswell @mikecrittenden :(

**Comment by mobilecarbs** [comment]
Yes, please let us know when this is done. I use this extension on a daily basis, its essential to my workflow. Thanks!

**Comment by ambrt** [comment]
The work around is to manually add
```
    height: 500px;
    overflow: scroll;
```
to `div.panel-group`  via Chrome Dev Tools.

**Comment by mikecrittenden** [comment]
This should (finally) be fixed in the latest version.
