### ISSUE TITLE
Add Right Click as a modifier

### ISSUE THREAD

**Issue by jesse9212** [mikecrittenden/shortkeys#155]
Just one example:

Right Click + Scroll Wheel = Page Up or Page down

The regular scroll goes by a couple lines but holding right click and scrolling does Page Up or Page Down

**Comment by mikecrittenden** [comment]
Shortkeys is keyboard only - maybe check out https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en for similar things but with mouse buttons/gestures.
