### ISSUE TITLE
Can "Incognito mode" be disabled ?

### ISSUE THREAD

**Issue by av930** [mikecrittenden/shortkeys#157]
I remapped shortcut "Ctrl+Shift+n" that originally open incognito mode with "do nothing"
but It won't work.
Thanks in advance. 
from JK. 
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Version 65.0.3325.162 (Official Build) (64-bit)
* Operating System and version: Windows 10

## Expected Behavior

do nothing.

## Current Behavior

open incognito mode window

## Steps to Reproduce (for bugs)

1. remap "Ctrl+Shift+n" to do nothing.
2. try Ctrl+Shift+n

**Comment by mikecrittenden** [comment]
Unfortunately not - this isn't something that Chrome allows you to do.
