### ISSUE TITLE
Have tried everything for "run javascript' shortkey -- nothing has worked

### ISSUE THREAD

**Issue by sariepaulso** [mikecrittenden/shortkeys#159]
We have been using this chrome extension at work without any problems setting people up when they want to utilize the tool to gather information from LinkedIn. When we tried to set up someone else's chrome to do the same thing, it wouldn't work. We've restarted her computer, cleared her cache and cookies, reset her settings, deleted the extension and redownloaded it, tried different sets of javascript code, etc. Nothing has worked. Can you please give us more troubleshooting to try? Thank you.

**Code 1 we tried**
var full_name = $(‘#topcard h1’).first().text();
var company = $(‘h5 a’).first().text();
var title = $(‘#profile-experience h4 a’).first().text();
var url = document.URL.split(‘?’)[0];
// var publicUrl=“”;

//publicUrl no longer used; no need to try and retrieve
// try {
//   publicUrl = document.getElementsByClassName(“public-profile searchable”)[0].childNodes[0].href;
// } catch(e) {
// }

//recentDate not used; no need to try and retrieve
// var recentDate = “”;
// try {
//   recentDate = document.getElementsByClassName(“date-range”)[0].childNodes[0].wholeText;
// } catch(e) {
// }

//old result format using publicUrl
// var result = full_name +
          // ‘|' + company +
          // ‘|' + title +
          // ‘|' + url +
          // ‘|' + publicUrl;

var result = full_name +
          ‘|' + company +
          ‘|' + title +
          ‘|' + url;

window.prompt(‘Woohoo!’, result);

**Code 2 we tried**
var full_name = $('#topcard h1').first().text();
var company = $('h5 a').first().text();
var title = $('#profile-experience h4 a').first().text();
var url = document.URL.split('?')[0];
var publicUrl="";
try {
   publicUrl = document.getElementsByClassName("public-profile searchable")[0].childNodes[0].href;
} catch(e){}
var recentDate="";
try {
  recentDate = document.getElementsByClassName("date-range")[0].childNodes[0].wholeText;
} catch(e) {}

string = full_name+'|'+ company+'|'+title+'|'+url+'|'+publicUrl;
window.prompt("YAY YAY YAAAAY!", string);

*********We are not developers by any means, so please no judgment on this code unless it's to potentially help with the current issue at hand. 

We've tried both sets of code at different times using the run javascript behavior. We've followed the additional troubleshooting steps about refreshing the page and even hard-quit chrome. Nothing has worked. Please help us. ***********

**Comment by mikecrittenden** [comment]
Closing some old tasks, feel free to comment if this is still an issue. 

In this case, I'd try running the code in the browser console first and confirm it works there before adding it to shortkeys.
