### ISSUE TITLE
how to setup ctrl+q to Press ENTER

### ISSUE THREAD

**Issue by mrdomsx** [mikecrittenden/shortkeys#160]
how to setup ctrl+q to Press ENTER

**Comment by krischanglaesel** [comment]
fow what exactly do you need this

**Comment by mrdomsx** [comment]
I want when press ctrl+q as Enter key

**Comment by krischanglaesel** [comment]
https://www.w3schools.com/js/js_events_examples.asp

maybe you can do it with a javascript and send enter key as an event ?
