### ISSUE TITLE
Shortcut keys don't work while on textarea or input fields

### ISSUE THREAD

**Issue by klaritan** [mikecrittenden/shortkeys#163]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox latest
* Operating System and version: Win 10

## Expected Behavior

Shortcut keys working

## Current Behavior

Shortcut keys not working

## Steps to Reproduce (for bugs)

1. Focus on input field or text area
2. Try to use shortcut key like going previous tab

**Comment by mikecrittenden** [comment]
Try this: https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#triggering-shortcuts-while-typing-in-form-fields

**Comment by klaritan** [comment]
@mikecrittenden Thank you and sorry I missed that!
