### ISSUE TITLE
Can not bind ctrl+< or alt+<

### ISSUE THREAD

**Issue by FatCash** [mikecrittenden/shortkeys#164]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome  Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version: Win 7 SP1

## Expected Behavior
I am unable to bind ctrl+< or alt+<, but binding solely < works.
I am using standard Swedish keyboard layout where < is a dedicated key (no modifiers involved).
The same with § key, not possible to bind it with any modifiers. How to solve this?

**Comment by mikecrittenden** [comment]
Good question. I think this would actually be a question for https://github.com/ccampbell/mousetrap/issues since that's the library that we're using for keyboard shortcuts. I'm not sure how to test/work on < or §, having a standard US layout.
