### ISSUE TITLE
Document the Windows key

### ISSUE THREAD

**Issue by davidhedlund** [mikecrittenden/shortkeys#166]
Can you please document the name of the Windows key (known as the SUPER key in GNU GNOME) in https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#supported-keyboard-shortcuts ?

Is it **win**, or **windows**?

**Comment by pepBR** [comment]
+1

**Comment by markstos** [comment]
Or, it's not possible, just note that here and close the ticket.

**Comment by davidhedlund** [comment]
> Or, it's not possible, just note that here and close the ticket.

What?

**Comment by mikecrittenden** [comment]
I don't have a way to test on a Windows machine, but just looking at https://github.com/ccampbell/mousetrap/issues/81 (which is the keyboard shortcut library that Shortkeys uses), it looks like `meta` should work for the Windows key. Can someone confirm that?

**Comment by davidhedlund** [comment]
I don't use Windows either. Can you confirm that it doesn't work on Windows @markstos ?

**Comment by markstos** [comment]
I don't use Windows either. I use Linux, where I know it as the "Super" key. The keycode is the same as the one also sent by the command on Mac, I believe.

**Comment by davidhedlund** [comment]
> I don't use Windows either. I use Linux, where I know it as the "Super" key. The keycode is the same as the one also sent by the command on Mac, I believe.

Thanks.

**Comment by wielinde** [comment]
Having Firefox on Ubuntu using the symbol `⌘` instead of `super` worked for me. Just copy it from here and paste it when configuring.

**Comment by piotr-dobrogost** [comment]
First raised in https://github.com/mikecrittenden/shortkeys/issues/120
Information on what to use for Windows key is really needed in the docs.
