### ISSUE TITLE
Doesn't take effect immediatly

### ISSUE THREAD

**Issue by davidhedlund** [mikecrittenden/shortkeys#168]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Firefox 59.0.2 64-bit
* Operating System and version: GNU/Linux

## Expected Behavior
It should work when I reload the tab.

## Current Behavior
The add-on says this when I hit the Save button:
> Your settings were saved! Reload your tabs to use your new shortcuts.

## Steps to Reproduce (for bugs)
1. Add anything
2. Save
3. Reload the tabs.
4. Test it -- it won't work

**Comment by mikecrittenden** [comment]
I believe this should be fixed with the latest release (see https://github.com/mikecrittenden/shortkeys/releases) but feel free to comment if not.
