### ISSUE TITLE
Make it possible to add custom link

### ISSUE THREAD

**Issue by davidhedlund** [mikecrittenden/shortkeys#169]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Firefox 59.0.2 64-bit
* Operating System and version: GNU/Linux

## Expected Behavior
I expected it to be possible to **Add a custom link** in these Behaviors:
* Open bookmark/bookmarklet in current tab
* Open bookmark/bookmarklet in new tab
* Open bookmark/bookmarklet in new background tab

## Current Behavior
You can only **Select bookmark...** in these Behaviors:
* Open bookmark/bookmarklet in current tab
* Open bookmark/bookmarklet in new tab
* Open bookmark/bookmarklet in new background tab

**Comment by mikecrittenden** [comment]
This is what the "Jump to tab by URL" action does. It allows you to open a custom URL if you don't already have it open.
