### ISSUE TITLE
Feature request: Select by ID to be pin aware.

### ISSUE THREAD

**Issue by michaelcadilhac** [mikecrittenden/shortkeys#170]
I'd like to have Alt-1 to Alt-9 to pertain to my pinned tabs, and Ctrl-1 to Ctrl-9 to my unpinned tabs.  I've quickly implemented that (see [pin-aware.patch](https://github.com/mikecrittenden/shortkeys/files/1887605/pin-aware.patch.txt) ) but there are probably more aesthetic ways to do it.

In passing, that's a shame that the custom keybindings don't work in a text box.  I may have to revert to Firefox just for that reason…

Thanks for the great work on that extension!

**Comment by mikecrittenden** [comment]
I don't hate this idea but the fact that it adds decent complexity combined with the fact that you're the first person I've seen ask for it makes me think that maybe we should hold off.
