### ISSUE TITLE
can't even get started

### ISSUE THREAD

**Issue by barnarddale** [mikecrittenden/shortkeys#172]
I failed at step 2. I installed it, but what configuration page are you talking about? How do I get to it? Please clarify.

## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
This is an old issue, but for anyone else finding this, click on the extension icon and then click "Options"
