### ISSUE TITLE
Doesn't work in Chrome.

### ISSUE THREAD

**Issue by nrsrymj** [mikecrittenden/shortkeys#173]
Pretty much self-explanatory by the title. I have reloaded tabs after saving, closed out and restarted Chrome, but none of the key combos work.

* Shortkeys version: 2.2.7
* Browser name and version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* Operating System and version: Windows 10 home

The key combos should work...

...But they don't.

**Comment by pherde** [comment]
Same problem here, chrome 66.0.3359.139  (Official Build) (64-bit) - Windows 10

**Comment by nrsrymj** [comment]
Yeah so any solutions or what?

**Comment by pherde** [comment]
Curious... after rebooting windows the extension worked!

**Comment by ddcgh** [comment]
Doesn't work for me in Chrome 68.0.3440.106 (Official Build) (64-bit)

**Comment by lex0r** [comment]
Same issues for me, can't define a shortcut - the extension can't capture any combinations and the whole add process stalls.
