### ISSUE TITLE
Focus searchbar (Firefox) shortcut?

### ISSUE THREAD

**Issue by randomnf** [mikecrittenden/shortkeys#174]
Is it possible to add this ability to your addon?

On ubuntu i cant focus to Firefox searchbar with CTRL+E (it works only on Windows), i can do this only with CTRL+J / CTRL+K, but J and K are so far away from CTRL to do this with one hand =)

**Comment by Koc** [comment]
Have same problem. Is there way to rebind `F6` to `ctrl+q`?

**Comment by mikecrittenden** [comment]
Sadly no, webextension doesn't support this as far as I'm aware.
