### ISSUE TITLE
Would like added support for search functions and expanded function key assignment

### ISSUE THREAD

**Issue by jefferysmall** [mikecrittenden/shortkeys#176]
I can search the web page using Ctrl-F with Ctrl-G or F3 as Find Next and Ctrl-Shift-G or Shift-F3 as find previous.  I would like to remap these function to other function keys on the keyboard, but these functions and keys are not listed.

## Your Environment
Xubuntu 17.10
Firefox 56.0.2
Shortkeys 2.2.7
Keyboard: Sun Type 6

## Expected Behavior
For example, allow remapping of Find Next to the Insert key or F22 on my keypad.

## Current Behavior
These search functions are not currently supported and some of the keys on my keyboard are not supported.

## Steps to Reproduce (for bugs)
This is an enhamcenet request.

**Comment by mikecrittenden** [comment]
Unfortunately the extension API doesn't let us provide custom shortcuts for browser search/search next. ☹️
