### ISSUE TITLE
No Config in Firefox 48 (Mac)

### ISSUE THREAD

**Issue by BrianStegner** [mikecrittenden/shortkeys#178]
The config page shows no enter/submit/Save... nothing, just the intro blurbs about the extension
## Your Environment

* Shortkeys version: Latest
* Browser name and version: Firefox 48 (Mac)
* Operating System and version: macOS 10.3.5

## Expected Behavior

There's supposed to be an area at the bottom of the config page where we can choose a label, input the shortcut, itself, decide if it will also work in forms, etc, and SAVE

None of these are visible

It should work in FF 48 as it does in all other versions, yeah?

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
