### ISSUE TITLE
Special characters on keyboard

### ISSUE THREAD

**Issue by agiz10** [mikecrittenden/shortkeys#179]
Combination of ctrl + special characters on keyboard do not seem to be working.
I am trying to assign ctrl+đ and ctrl+ž buttons for close tab and undo close tab. They work correctly with ctrl+o, ctrl+i (for testing purpuses). So special characters are the problem
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 60
* Operating System and version: Windows 10

## Expected Behavior

ctrl+ž is set to close tab. When pressed it should close tab.
ctrl+đ is set to reopen last closed tab. When pressed it should reopen last closed tab.

## Current Behavior

ctrl+ž is set to close tab. When pressed nothing happenes
ctrl+đ is set to reopen last closed tab. When pressed nothing happenes

## Steps to Reproduce (for bugs)

for testing i tried ctrl+o for close tab and it works like expected

**Comment by agiz10** [comment]
I found a workaround for my problem. I use AutoHotkeys to substitute the keyboard commands. Just thought i would share this if anyone has similar problem.

**Comment by akaihola** [comment]
@agiz10, what is AutoHotkeys? I can't find such an extension for Firefox or Chrome. Is it specific to some operating system or distribution? I have no such thing on my Fedora and Ubuntu systems.

Anyway I wonder if special characters in key combinations could be supported by re-using the same mechanism which browsers themselves use to define shortcuts?

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
