### ISSUE TITLE
Mouse Buttons

### ISSUE THREAD

**Issue by DZaio** [mikecrittenden/shortkeys#180]
I'm trying to configure mouse 4 button to run ctrl+tab. My behavior is obviously next tab. What is the "keyboard" shortcut? I tried "XButton1" and "XButton4" but those didn't work.

**Comment by mikecrittenden** [comment]
Shortkeys doesn't support mouse buttons, but there are some other extensions for that, such as https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en
