### ISSUE TITLE
Menu key disable action support

### ISSUE THREAD

**Issue by savinov** [mikecrittenden/shortkeys#181]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Chrome 66.0.3359.170
* Operating System and version: Ubuntu 14.04.5

## Expected Behavior
I'd like to disable actions for the Menu button key (which pops up the context menu).

## Current Behavior
The extension doesn't support it. Please try to make it.

## Steps to Reproduce (for bugs)

1. add new keyboard shortcut
2. in 'keyboard shortcut' field type: 'Menu' or 'menu'
3. in 'behavior' select 'disable' or anything else
4. nothing is changed: context menu pops up as usual

**Comment by mikecrittenden** [comment]
Unfortunately the extension API doesn't support this.
