### ISSUE TITLE
Can't seem to disable Cntr-t shortcut

### ISSUE THREAD

**Issue by xeraphax** [mikecrittenden/shortkeys#182]
Not sure if this can do it, but I mapped control-t to do nothing if pressed but it doesn't seem to work. 

Can't work out if this is deliberate or not.

## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Version 66.0.3359.139 (Official Build) (64-bit)
* Operating System and version: Windows 10 (latest update)

## Expected Behavior
 Unsure it's a bug, but would hope that having ctrl+t Do nothing (disable browser shortcut) should work.
 Either have it disable to give a message that it's not supported.

## Current Behavior
 It has no effect.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Sadly there are some browser shortcuts that an extension is not allowed to disable/alter, and this is one of them.
