### ISSUE TITLE
Hotkey suggestion to collect environmental information

### ISSUE THREAD

**Issue by sterbalr** [mikecrittenden/shortkeys#183]
It would be nice to have a hotkey that generated the Environmental information for this template. Is that possible?

## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Can you elaborate on what you mean by "Environmental information"?

**Comment by mikecrittenden** [comment]
Closing but feel free to comment with more info and I'm happy to reopen.
