### ISSUE TITLE
Extension option menu shakes

### ISSUE THREAD

**Issue by user8446** [mikecrittenden/shortkeys#185]
* Shortkeys version: 2.2.7
* Browser name and version: Chrome 67.0.3396.56 Beta
* Operating System and version: W10

The extension options menu randomly shakes to the point where you can't select options. I tried to reproduce this with other extension options both with ones that open settings in a tab and ones that open with an overlay type style like w/ shortkeys and could not.

**Comment by fernandoslemos** [comment]
I have the same problem when i try to create shortcut to the following javascript

`javascript:(function() {try{var e_m64 = "VkVSU0lPTiUyMEJVSUxEJTNEODM1MDMwNyUyMFJFQ09SREVSJTNEQ1IlMEFUQUclMjBQT1MlM0QxJTIwVFlQRSUzRFREJTIwQVRUUiUzRFRYVCUzQUNhc2VzJTBBVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RBJTIwQVRUUiUzRElEJTNBQnV0dG9uX05ld0Nhc2UoU3VwcG9ydCklMEEnVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RBJTIwQVRUUiUzRElEJTNBQnV0dG9uX05ld0Nhc2UlMEFUQUclMjBQT1MlM0QxJTIwVFlQRSUzRFNFTEVDVCUyMEZPUk0lM0RJRCUzQUVudHJ5Rm9ybSUyMEFUVFIlM0RJRCUzQWNhc2VfcHJvYmxlbXN1YnR5cGUlMjBDT05URU5UJTNEJTI1RnVuY0FwbCUwQVRBRyUyMFBPUyUzRDElMjBUWVBFJTNEU0VMRUNUJTIwRk9STSUzRElEJTNBRW50cnlGb3JtJTIwQVRUUiUzRElEJTNBY2FzZV9wcm9kbGluZSUyMENPTlRFTlQlM0QlMjUxNSUwQVRBRyUyMFBPUyUzRDElMjBUWVBFJTNEU0VMRUNUJTIwRk9STSUzRElEJTNBRW50cnlGb3JtJTIwQVRUUiUzRElEJTNBY2FzZV9wcm9kdXRvJTIwQ09OVEVOVCUzRCUyNTQ0JTBBJTBBUFJPTVBUJTIwJTIyQXNzdW50byUzQSUyMiUyMCFWQVIxJTBBU0VUJTIwIVZBUjIlMjBFVkFMKCUyMnZhciUyMHN0ciUzRCclN0IlN0IhVkFSMSU3RCU3RCclM0IlMjB2YXIlMjByZXMlMjAlM0QlMjBzdHIuc3Vic3RyaW5nKDAlMkMzOSklM0IlMjByZXMlM0IlMjIpJTBBVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RJTlBVVCUzQVRFWFQlMjBGT1JNJTNESUQlM0FFbnRyeUZvcm0lMjBBVFRSJTNESUQlM0FjYXNlX2Rlc2NyaXB0aW9uJTIwQ09OVEVOVCUzRCU3QiU3QiFWQVIyJTdEJTdEJTBBU0VUJTIwIVZBUjIlMjBFVkFMKCUyMiclN0IlN0IhVkFSMSU3RCU3RCcucmVwbGFjZSglMkYlQzIlQUIlMkZnJTJDJTIwJyUzQ2JyJTNFJyklM0IlMjIpJTBBVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RURVhUQVJFQSUyMEZPUk0lM0RJRCUzQUVudHJ5Rm9ybSUyMEFUVFIlM0RJRCUzQWNhc2VfcHJvYmxlbW5vdGUlMjBDT05URU5UJTNEJTdCJTdCIVZBUjIlN0QlN0QlMEFQUk9NUFQlMjAlMjJTb2x1JUMzJUE3JUMzJUEzbyUzQSUyMiUyMCFWQVIxJTBBU0VUJTIwIVZBUjMlMjBFVkFMKCUyMiclN0IlN0IhVkFSMSU3RCU3RCcucmVwbGFjZSglMkYlQzIlQUIlMkZnJTJDJTIwJyUzQ2JyJTNFJyklM0IlMjIpJTBBVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RURVhUQVJFQSUyMEZPUk0lM0RJRCUzQUVudHJ5Rm9ybSUyMEFUVFIlM0RJRCUzQWNhc2Vfc29sdXRpb25ub3RlJTIwQ09OVEVOVCUzRCU3QiU3QiFWQVIzJTdEJTdEJTBBVEFHJTIwUE9TJTNEMSUyMFRZUEUlM0RJTUclMjBBVFRSJTNESUQlM0FTZWFyY2hTbWFsbEFkdmNhc2VfcHJpbWFyeXBlcnNvbmlkSU1HJTBBUEFVU0UlMEFUQUclMjBQT1MlM0QyJTIwVFlQRSUzREElMjBBVFRSJTNESUQlM0FCdXR0b25fU2F2ZSUwQVdBSVQlMjBTRUNPTkRTJTNEMSUwQVRBRyUyMFBPUyUzRDElMjBUWVBFJTNEQSUyMEFUVFIlM0RJRCUzQUJ1dHRvbl9DbG9zZUNhc2UlMEFXQUlUJTIwU0VDT05EUyUzRDElMEFUQUclMjBQT1MlM0QyJTIwVFlQRSUzREElMjBBVFRSJTNESUQlM0FCdXR0b25fU2F2ZSUwQSUwQVRBRyUyMFBPUyUzRDElMjBUWVBFJTNEQSUyMEFUVFIlM0RJRCUzQUJ1dHRvbl9Db250aW51ZQ==", n64 = "JTIzQVBUX0ZVTkNfUmV0YWlsLmlpbQ==";if(!/^(?:chrome|https?|file)/.test(location)){alert('iMacros: Open webpage to run a macro.');return;}var macro = {};macro.source = decodeURIComponent(atob(e_m64));macro.name = decodeURIComponent(atob(n64));var evt = document.createEvent("CustomEvent");evt.initCustomEvent("iMacrosRunMacro", true, true, macro);window.dispatchEvent(evt);}catch(e){alert('iMacros Bookmarklet error: '+e.toString());}}) ();`

Window of options menu raise and i cant see the Save button

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
