### ISSUE TITLE
white-list

### ISSUE THREAD

**Issue by sibi-1** [mikecrittenden/shortkeys#186]
the extension is great..thank you.
only 1 thing is needed:
  **a WHITELIST**

i need to use some sites   **without**  the shortcuts.
CAN YOU MAKE AN OPTION?

THANK YOU AGAIN

**Comment by mikecrittenden** [comment]
Each individual shortcut has a "Settings" section where you can include/exclude specific sites.

**Comment by knoajp** [comment]
I've assigned 50-ish shortcut keys.
So it's quite convenient if I can specify a global BLACKLIST in one place.
