### ISSUE TITLE
js not getting executed

### ISSUE THREAD

**Issue by ArpitQA** [mikecrittenden/shortkeys#187]
## Your Environment

* Shortkeys version: : 2.2.7
* Browser name and version: Chrome 66.0.3359.181
* Operating System and version: Windows 10 

## Expected Behavior
I have a Javascript and want to trigger it on a combination of a hotkey (shift+q) but that does not seem to be working. My JS is just clicking a link based on the xpath which is correct

## Current Behavior

No JS triggered and no error in console

## Steps to Reproduce (for bugs)

Create a hotkey with any combination and set to run a javascript
JS Code = $x("//a[contains(text(),'Bulk upload')]")[0].click()
I added the website as well in the allowed as well such that below is my json - 
[{"action":"javascript","activeInInputs":true,"blacklist":"whitelist","code":"$x(\"//a[contains(text(),'Bulk upload')]\")[0].click()","exported":true,"key":"shift+q","open":true,"sites":"https://XXXXXXX.COM","sitesArray":["XXXXXXX.COM"]}]

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
