### ISSUE TITLE
Suggestion: Open Link in New Tab

### ISSUE THREAD

**Issue by GoGoGogleos** [mikecrittenden/shortkeys#188]
## Your Environment

* Shortkeys version:2.2.7
* Browser name and version: Google Chrome 66.0.3359.181 64-Buit
* Operating System and version:Windows 10, idk the newest

## Expected Behavior

Was hoping for a way to change Open link in New Tab from ctrl+LMB to Mouse Button 2(I have 2 thumb buttons) + LMB
## Current Behavior

Does not have option to change this
## Steps to Reproduce (for bugs)

1.Cream together 1 cups of softened butter and 1 cups of white sugar and 1/2 cup packed brown sugar. Then add 2 eggs and 1 teaspoon vanilla extract and cream together. Preheat oven to 375 F
2.Combine 3 cups flour, 1 teaspoon salt, 1 teaspoon baking soda and then add to butter mixture.
3. Add 2 cups semi-sweet chocolate chips and mix. Prepare a buttered baking sheet.
4. Form dough into small balls and place on sheet 2 inches apart and then bake 10 minutes and let cool.
5. Open Google Chrome, click the Shortkeys shortcut in the upper right corner, try to change Open Link in New Tab.
6. Fail at this, but eat cookies to avoid sadness.

**Comment by mikecrittenden** [comment]
Shortkeys doesn't support the mouse, but check out https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en
