### ISSUE TITLE
Feature request: Allow "jump to tab" action under Chrome's keyboard shortcuts

### ISSUE THREAD

**Issue by user8446** [mikecrittenden/shortkeys#190]
Currently this isn't an option in shortkeys. Chrome does allow this though. Please see the following extension that does exactly this:

https://chrome.google.com/webstore/detail/4-smart-shortcuts/fmmofgdcmllajpdnnpllmlffogijffan

Would this be possible to add to shortkeys?

Thank you for the development!

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
