### ISSUE TITLE
Send custom keycode events to running web app/page

### ISSUE THREAD

**Issue by xamde** [mikecrittenden/shortkeys#191]
Some webapps come with unchangeable, unusable shortcuts. E.g. the Google Keep app uses Ctrl+"["/"]" for (de)indenting list items.  But on my German keyboard, I cannot do this. I need to use "AltGr"+8 to even get at "[" printed. 

Idea: I use "shortkeys" and define my own shortkeys, e.g. "," and "." to emit "Ctrl+[" and "Ctrl+]".
I am not sure this is even possible in JS (to synthetically emit keyboard events, but what is NOT possible in JS nowadays?)

So instead of triggering browser behavior I would like to control the running web app.

Can I help adding this?

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
