### ISSUE TITLE
Assigning search/search next to function keys

### ISSUE THREAD

**Issue by jefferysmall** [mikecrittenden/shortkeys#193]
I want to assign browser search (Ctrl-F) and search next (Ctrl-G) to function keys, but am unsure how to do this as these functions are not listed in the Behavior list.  Am I missing something obvious?  Can I make assignments other than those provided in the list?  If not, can these search functions be added?  Thanks.

## Your Environment
Firefox 60.0.2
Shortkeys 2.2.7
Xubuntu 18.04

By the way, I posted a question regarding this back in April but never heard anything regarding it.  Can you comment on the the status?

https://github.com/mikecrittenden/shortkeys/issues/176

**Comment by AstroFloyd** [comment]
I second the request to add the find-in-page and (especiallly, since it also covers find-in-page) the find-again functionalities.  (I'd like to Ctrl-S my way through a page, since the command is guaranteed to *search*, but not to *find* any string in a given page).

**Comment by mikecrittenden** [comment]
Unfortunately the extension API doesn't let us provide custom shortcuts for browser search/search next. :(
