### ISSUE TITLE
Does not work RunJavascript with Firefox 

### ISSUE THREAD

**Issue by Alphaz1el** [mikecrittenden/shortkeys#195]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 60.0.2
* Operating System and version: Micr$s$ft Windows 7 Ultimate SP1 x64

## Steps to Reproduce (for bugs)

Keyboard shortcut: ctrl+shift+]
Behavior: **Run JavaScript**
(Optional) Label: Copy Title
Javascript code to run:
```
        var w = window._content;
        var d = w.document;
        var txt = d.title;
        const CLIPBOARD = Components.classes["@mozilla.org/widget/clipboardhelper;1"].getService(Components.interfaces.nsIClipboardHelper);
        CLIPBOARD.copyString(txt);
```

**Comment by Alphaz1el** [comment]
If you do not intend to UPDATE, please stop publishing and delete it.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
