### ISSUE TITLE
chrome shotcut doesn't work

### ISSUE THREAD

**Issue by empleat** [mikecrittenden/shortkeys#196]
Tabs don't cycle using hotkey

## Your Environment

* Shortkeys version:3.1
* Browser name and version:Chrome stable
* Operating System and version:Windows 10 17.134

## Expected Behavior
i set shotcut to alt+c, or ctrl+shift+f2 and recents tabs menu should show, or any tabs should cycle (i restarted chrome and reloaded tabs)

## Current Behavior

Tabs didn't cycle and tab menu didn't show
EDIT: now it doesn't even save shotcut, when i click on save and it says saved and than after i restart chrome, shotcut field is blank.

## Steps to Reproduce (for bugs)

1.Just reload tabs, or restart chrome and pres ctrl+tab and than hotkey like alt+c to cycle tabs
2.
3.
4.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
