### ISSUE TITLE
When switching to next/previous tab, skip over "hidden" tabs

### ISSUE THREAD

**Issue by yennor** [mikecrittenden/shortkeys#197]
When you have "simple task group" installed, and you have shortcuts for previous tab/next tab and you use the short while the first respectively the last tab in a group is activated, firefox will jump to the last respectively first tab of an other group, instead of cycling only in the same group.
When you use ctrl-tab ctrl-shift-tab Firefox cycles only in the same group (it jumps from the last to the first task in  the same group and vice versa).
I'm not sure if that is a bug of the shortkeys plugin or of "simple task groups".

* Shortkeys version: 2.2.7
* Browser name and version: firefox 61
* Operating System and version: Debian Linux Stable

## Expected Behavior
shortcuts for Previous/Next tab should behave the same as ctrl-tab ctrl-shift-tab

## Current Behavior
see above

**Comment by yennor** [comment]
I've got a reply from the creator of simple tab groups.
It has to do with hidden tabs, which shortkeys seems to ignore.
Here:
https://github.com/Drive4ik/simple-tab-groups/issues/204#issuecomment-403486323

**Comment by yennor** [comment]
Is there any chance that problem would be resolved? It drives me crazy.

It should be mainly about to check if the next tab is hidden, if yes, don't change to it, but the next one which is not hidden.

**Comment by mikecrittenden** [comment]
I'm not sure that I can really do anything here because it seems that "hidden" tabs are a Firefox only thing, and are not supported in Chrome, and this extension tries to support both of them. See https://developer.chrome.com/extensions/tabs#method-query and note that there is no "hidden" filter there.

**Comment by yennor** [comment]
One could argue that like that, Firefox isn't completely supported, only chrome ;-).
anyway. Wouldn't it be possible:
- to have a browser detection and change the query depending on the browser?
- Maybe chrome doesn't throw an error on an unknown query property and just ignores it?
- If it throws an error, have a try/catch around the query? (ok, I admit that this solution is especially ugly ;-) )

**Comment by mikecrittenden** [comment]
@yennor would you be willing to work on a PR? I'd be happy to review that.

**Comment by yennor** [comment]
sure. But not before new year's eve

**Comment by mikecrittenden** [comment]
@yennor just bumping this - any plans to work on it? If not in the near future, I'll close the issue for now but PRs are welcome anytime.

**Comment by yennor** [comment]
alright. It took me longer than expected. There's always more work around than one expects. but here we go:
 #310

**Comment by mikecrittenden** [comment]
At long last, I have brought in this change. I simplified it just a bit: https://github.com/mikecrittenden/shortkeys/commit/81af80c5e248f48e291f02fff2b8e58f668437ce

**Comment by yennor** [comment]
cool! thanks!
