### ISSUE TITLE
Chromebook Delete Key

### ISSUE THREAD

**Issue by HarveyMechanic** [mikecrittenden/shortkeys#198]
## Your Environment

* Shortkeys version: Version: 2.2.7
* Browser name and version: Chromebook Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System and version: Chromebook Version 67.0.3396.99 (Official Build) (64-bit)

Many people are upset that Chromebooks do not have a delete key. To delete, we need to use Alt+Backspace and that is hard to do without taking right hand off starting position on keyboard. I don't know Javascript. Can you give me the Javascript to run Alt+Backspace with a key combination like Alt+z?  I did find out that the Alt-Backspace keyCode = 46  

Thank you.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
