### ISSUE TITLE
How to add a Shortkey to open an url ???

### ISSUE THREAD

**Issue by liwenjing93** [mikecrittenden/shortkeys#200]
Hi, my question is simple, I want to add a Shortkey to open an url that I want. Example: chrome://extensions/, or an another specific website. 

I can't find any option in that extension can help me about that.

Thanks, 

------- 

This is my Environment: 

* Shortkeys version:  2.2.7
* Browser name and version:  Google chrome v67.0.3396.99 
* Operating System and version: Windows 7

**Comment by mikecrittenden** [comment]
The "Jump to tab by URL" action supports this. It allows you to jump to a tab if that URL is already in a tab, and otherwise it'll open it in a new tab.
