### ISSUE TITLE
Does not work on github.com

### ISSUE THREAD

**Issue by jtgd** [mikecrittenden/shortkeys#201]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 61.0.1
* Operating System and version: Arch Linux 4.17.6

## Expected Behavior

I use javascript to save bookmarks. When I press the shortcut it pops up a window to enter tags, then it forwards it to a local URL. I expect it to work on every web page. 

## Current Behavior

Works on every page except one on github.com. Nothing happens when the shortcut is pressed. It does not seem to matter what key it is bound to (I've tried many).

## Steps to Reproduce (for bugs)

1. Visit page on github.com
2. Press shortcut key assigned to javascript.
3. Note how nothing happens.
4.

FYI, this is the javascript:

javascript:location.href='http://192.168.1.2:38080/x/'+encodeURIComponent(location.href)+'/'+encodeURIComponent(document.title)+'/'+encodeURIComponent(prompt('Tags?'))

**Comment by DZaio** [comment]
I've got the same issue. I have the key next to 1 bound to change tabs (shift+tab). When every I press it, it will not swap to github.

(Also how would I use mouse button 4 if you happen to know)

**Comment by mikecrittenden** [comment]
Github must be implementing its own keyboard shortcuts in a way that conflicts with Shortkeys. There's not much that we can do about that, other than suggest that you try to use keyboard shortcuts that aren't also used by sites that you visit often.
