### ISSUE TITLE
Menu key not working

### ISSUE THREAD

**Issue by PlagueCze** [mikecrittenden/shortkeys#202]
* Shortkeys version: 2.2.7
* Browser name and version: Chrome, 68.0.3440.106
* Operating System and version: Win 10 home

## Expected Behavior
Press context menu key to open new tab.
https://i.stack.imgur.com/kF3jU.png

## Current Behavior
When I press menu key, usual context menu pops up.

## Steps to Reproduce (for bugs)
1. Keyboard shortcut="menu"; Behavior="new tab".
![shortkeys](https://user-images.githubusercontent.com/17255105/44159404-8f64b000-a0b7-11e8-85d0-ff873515409a.png)

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
