### ISSUE TITLE
Firefox user: Some form fields are not recognized as such

### ISSUE THREAD

**Issue by rlsx** [mikecrittenden/shortkeys#203]
Firefox user: Some form fields are not recognized as such.
So, if shortcuts are assigned to alpha-letters, or to cursor keys, the filed becomes unusable.
A stopgap measure would be to have a Button to enable/disable the extension.
An example: Try to comment on:
https://foreignpolicy.com/2018/08/15/trump-will-regret-changing-his-mind-about-qatar/
(unfortunately, you have to register first, free of course).

Thanks for the excellent work!

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
