### ISSUE TITLE
If you do not intend to UPDATE, please stop publishing and delete it.

### ISSUE THREAD

**Issue by Alphaz1el** [mikecrittenden/shortkeys#204]
**If you do not intend to UPDATE, please stop publishing and delete it.**

**Comment by Isaac4fun** [comment]
This is an incredibly useful extension and if you do not want to use it, simply uninstall it and be on your way. The people who made this put effort into making our lives easier.

**Comment by mikecrittenden** [comment]
Back at it now, sorry for the very long hiatus.
