### ISSUE TITLE
"up arrow" and "down arrow" functionality to navigate search bar suggestions?

### ISSUE THREAD

**Issue by vistuleB** [mikecrittenden/shortkeys#205]
I would like to creating key bindings that will allow me to navigate the search (url) bar suggestions without moving my fingers from the home row.

Currently these url suggestions (or search suggestions, depending) are navigatable with the up and down arrows.

Are the search/url suggestions accessible from javascript?

**Comment by agarrido19** [comment]
https://superuser.com/questions/509192/tab-enter-no-longer-taking-me-to-first-google-search-result-in-chrome/1235034#1235034

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
