### ISSUE TITLE
Apply custom css with a shortcut

### ISSUE THREAD

**Issue by srustamo** [mikecrittenden/shortkeys#206]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox Quantum 62
* Operating System and version: OSX 10.13.6 

## Expected Behavior
Is it possible to apply custom CSS with a shorcut? Specifically, userChrome.css in `chrome` dir in the profile. The aim is show/hide tabbar.

**Comment by mikecrittenden** [comment]
I don't believe that's possible with the extension API.
