### ISSUE TITLE
Running js in extension enviroment

### ISSUE THREAD

**Issue by cnwangjie** [mikecrittenden/shortkeys#207]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 62.0 (64-bit)
* Operating System and version: Archlinux

## Expected Behavior

Hope it is possible to execute a js script in extension enviroment so that I can send message with another addon and implement more advance action.

## Current Behavior

Currently it just can execute script in the page.

**Comment by mikecrittenden** [comment]
Sadly no, that isn't supported.
