### ISSUE TITLE
I often must take double action to apply my shortcut

### ISSUE THREAD

**Issue by namly5036** [mikecrittenden/shortkeys#208]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome 61.0.3163.100
* Operating System and version: Window 7 Enterprise

## Expected Behavior

**I press only single action to apply my shortcut (as default)**

## Current Behavior

**I often must take double action to apply my shortcut**
**Single action is sometimes successful, sometimes unsuccessful**

## Steps to Reproduce (for bugs)

**1. Create shortcut "space+W" for "Close tab" action
2. Sometimes, i must press double action "space+w" to apply my shortcut.  (Hold down the space and press double the W key)
(Note: I do it outside input text)**

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
