### ISSUE TITLE
Is there a way to make a keyboard shortcut + mouse click?

### ISSUE THREAD

**Issue by estevamprada** [mikecrittenden/shortkeys#210]
I want to make something to close tabs...

Example: shift + left click

**Comment by mikecrittenden** [comment]
Shortkeys doesn't support the mouse, but check out https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en

**Comment by andriejs** [comment]
@crittermike THAT ISN'T RELATED TO THE FUCKING ISSUE. CRX MOUSE ISN'T THE THING THEY WERE SEARCHING FOR. THEY WANT A SIMPLE "rightclick" ACTION LIKE "ctrl+click" or "ctrl+rightclick" NOT THAT IDIOTIC PEICE OF SHIT.
