### ISSUE TITLE
Add ability to detatch tab ?

### ISSUE THREAD

**Issue by stuaxo** [mikecrittenden/shortkeys#211]
In the list of tab actions I couldn't see an action to detach a tab.

Not sure how possible it is, but in older keyboard shortcut addons it was possible

https://superuser.com/questions/881728/shortcut-key-to-detach-a-tab-in-firefox-move-tab-to-new-window

There is probably a better / different way of doing this now though.

**Comment by wmertens** [comment]
I experimented a little bit.

To detach, find out the tabId of the current tab, and then run `chrome.windows.create({tabId, focused: true})`

This will move the tab to a new window and focus it.

**Comment by AdamPS** [comment]
@wmertens Please can you explain how your suggestion solves the original problem?  If I create a shortcut to run javascript, chrome.windows.create or browser.windows.create are not defined.

**Comment by wmertens** [comment]
It needs to be implemented as a detachTab action in background.js

**Comment by AdamPS** [comment]
@wmertens Thanks for the reply.  Ah I think I understand - you are explaining how to add code to the shortkeys add-on to enable this feature.

I had the idea that you were explaining how I could configure shortkeys with a "Run Javascript" shortcut.

**Comment by alon91** [comment]
[Vimium](https://github.com/philc/vimium) seems to offer that feature via the `moveTabToNewWindow` command. Perhaps see how they implement it there?

![image](https://user-images.githubusercontent.com/35006176/61090079-20d8c100-a3f2-11e9-9691-9df49b5c41e1.png)

**Comment by uz-air** [comment]
@mikecrittenden can you please add this detach tab functionality in the shortkeys extension

**Comment by mikecrittenden** [comment]
There's already a "Move tab to new window" action which should accomplish this.
