### ISSUE TITLE
Shortcut for right click / context menu?

### ISSUE THREAD

**Issue by alon91** [mikecrittenden/shortkeys#214]
I'd love to be able to assign a shortcut that triggers a right mouse click to bring up the context menu. This can be done on the OS level for some operating systems ([Shift + F10](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts) in Windows, for example), but I'd love a cross-platform solution that I can define.

## Expected Behavior

- When cursor is in an input box, bring up relevant context menu
- When cursor is not in an input box, bring up the same context menu that would come up when hitting `Shift` + `F10` on Windows keyboard.

**Comment by mikecrittenden** [comment]
Hmm, from what I can tell, this isn't something that extensions have the power to accomplish.

**Comment by andriejs** [comment]
@crittermike EXTENSIONS HAVE ACCESS TO INJECT JAVASCRIPT. JAVASCRIPT CAN DO THAT.
