### ISSUE TITLE
Broken on Chrome 71

### ISSUE THREAD

**Issue by whatisjasongoldstein** [mikecrittenden/shortkeys#221]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome 71.0.3578.80
* Operating System and version: Mac OS 10.14

## Expected Behavior
Typing key combos should work

## Current Behavior
After Chrome updated itself this morning, it stopped working. Every combo registers but throws this error:

```
VM24 extensions::schemaUtils:115 Uncaught Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connectInfo)
    at Object.normalizeArgumentsAndValidate (VM24 extensions::schemaUtils:115)
    at Object.<anonymous> (VM19 extensions::binding:363)
    at Object.<anonymous> (VM29 extensions::runtime:56)
    at Object.handleRequest (VM19 extensions::binding:64)
    at Object.<anonymous> (VM19 extensions::binding:374)
    at Object.o.doAction (contentscript.js:1)
    at e (contentscript.js:1)
    at f (mousetrap.min.js:5)
    at g (mousetrap.min.js:5)
    at f (mousetrap.min.js:5)```

**Comment by mikecrittenden** [comment]
So far I'm not able to reproduce this - all shortcuts are still working for me in Chrome 71, whether they were created from the Shortkeys config or the Chrome extension page Keyboard Shortcuts settings. Can I get a screenshot of a specific shortcut that's failing for you?

**Comment by whatisjasongoldstein** [comment]
Yes. I can now reproduce it on two laptops.

Here's one of the commands exported:

```
[{
    "action": "openbookmark",
    "blacklist": "false",
    "bookmark": "Instapaper",
    "customName": "Instapaper",
    "exported": true,
    "key": "command+i",
    "open": true,
    "sites": "*mail.google.com*",
    "sitesArray": ["*mail.google.com*"]
}]
```

It's probably worth noting they're all bookmarklets, and the bookmarklets work fine.

And here's the screenshot:

![screenshot 2018-12-11 19 14 23](https://user-images.githubusercontent.com/377630/49838571-4678eb80-fd79-11e8-926e-1575d9f3e07b.jpg)

**Comment by whatisjasongoldstein** [comment]
It's odd that mail.google.com appears in the json. I have this active on all sites 🤔

**Comment by mastikhor** [comment]
i am having the same issue since updating to chrome 71

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
