### ISSUE TITLE
Can this fix Google Music miminize bug on ChromeOS?

### ISSUE THREAD

**Issue by markstos** [mikecrittenden/shortkeys#222]
## Your Environment

 * Chrome OS 72, developer channel
 * Shortkeys: 2.2.7

## Current Behavior

Google has a bug on Chrome OS that I'm trying to fix. 

Chrome OS uses Alt+- to minimize window. 
But Google Music uses "Alt+-" to "thumbs down" a song.

So you when you open Google Music on Chrome OS and try to minimize it with the standard shortcut... the music suddenly stops and progresses to the next song instead.

I was able to fix the issue with Shortkeys, but only in a Chrome window.  When say "Fix", 
When Google Music in it's own "app" window with no URL bar, the extension doesn't work, even though I can see it's loaded.

The Shortkey I've defined is to map "Alt+-" to "disable browser shortcut", and I've limited it to "play.google.com/music*"

## Expected Behavior

 * Even when run in an app window,  "Alt+-" handling by Google Music should be disabled and passed to the browser to minimize the window. 

## Steps to Reproduce (for bugs) ##

1. Run Google Music in an "app window" on Chrome OS (may behave the same on Linux, too).
2. Install "Alt+-" disable shortcut as described above
3. Try the shortcut. It should minimize the browser, not Thumbs Down a song.

**Comment by markstos** [comment]
I tried to solve the problem from a different angle using this extension:

I tried mapping "Super-H" to send "alt+-", in hopes that would minimize the window. I tried referring to the super key as both "command" and ⌘., but neither approach worked.

I'm using to using `Super-H` to "Hide" windows in Gnome, so that would be a good global shortcut to use instead of "Alt+-" if it can work. Thanks.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.

**Comment by markstos** [comment]
I have not tried the latest version of this extension to see if it resolves the issue. I worked around the issue by switching to the Android player on Chrome OS.
