### ISSUE TITLE
Media key support?

### ISSUE THREAD

**Issue by markstos** [mikecrittenden/shortkeys#223]
Is is possible to emulate the press of a media key?

This would be useful on Chrome OS when it's used with external keyboards that don't have media keys.

Chrome OS has limited built-in functionality to customize keyboard shortcuts.

**Comment by mikecrittenden** [comment]
Looks like no, this isn't support by the library we use for key bindings. See https://github.com/ccampbell/mousetrap/pull/398

**Comment by markstos** [comment]
My eventual workaround to was to use an external QMK-powered keyboard that allows me to customize any key combination to send media key events, which Chrome OS supports. In fact that solution allowed to me improve all the Chrome OS shortcuts which aren't customizable. :+1:
