### ISSUE TITLE
Not able to save long java script

### ISSUE THREAD

**Issue by mastikhor** [mikecrittenden/shortkeys#224]
* Shortkeys version: 2.2.7
* Browser name and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System and version: Windows 10 64-bit

I am trying to create a shortcut to run a javascript but the script has a very long single line code and when i type that in i am not able to click on save (shown in a pic below) as the settings box increases in size and the save button goes out of bounds and there is no way to scroll to right and click on save. I have tried zooming out but that does not helps either.
![9fdffb3d8b6c2d8503486e1755a4c6c7](https://user-images.githubusercontent.com/45901012/50130505-f7184b00-02a3-11e9-8f4b-67d3241f4697.png)

**Comment by mikecrittenden** [comment]
This should be fixed now that lines wrap.
