### ISSUE TITLE
feature : shortcut to mute all background tabs

### ISSUE THREAD

**Issue by uz-air** [mikecrittenden/shortkeys#225]
hi,
can you please add a shortcut to mute/unmute all background tabs? 
it will be really handy cause recently chrome removed a flag to mute by clicking (chrome://flags/#enable-tab-audio-muting)
another extension called mute tab (https://chrome.google.com/webstore/detail/mutetab/acofndgbcimipbpeoplfjcapdbebbmca) already supports but I don't want to download another extension.
if shortkeys already support it please tell me how to enable it if not please consider adding this feature.
thanks

**Comment by mikecrittenden** [comment]
Honestly Mute Tab seems like a better solution, because most people would want tabs to be muted by default, or mute an individual tab (which Shortkeys supports), rather than muting all of them via a keyboard shortcut.

**Comment by uz-air** [comment]
suppose am listening to a song in the background tab and browsing the web.
suddenly I see a video while browsing, now to watch the video I will have
to search the song tab and pause/mute it and come to the browsing tab.
all of this can be avoided by muting/unmuting background tab
Thanks & Regards
Uzair Adeel

**Comment by mikecrittenden** [comment]
Are you by any chance using a keyboard with media keys? I use media keys along with https://chrome.google.com/webstore/detail/key-socket-media-keys/fphfgdknbpakeedbaenojjdcdoajihik to solve the use case you mentioned.
