### ISSUE TITLE
bookmark this page shortcut

### ISSUE THREAD

**Issue by auralarch** [mikecrittenden/shortkeys#226]
Is it possible to customize the shortcut for bookmarking the current page?   That doesn't seem to be one of the behaviors, which seems strange to me; so I'm thinking perhaps I'm missing something.

## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version:  Firefox 60.4.0esr 
* Operating System and version: Windows 7 x64

## Expected Behavior
Ability to customize the shortcut for bookmarking the current tab/page

## Current Behavior
Can not find this option in the behavior list.
Perhaps it could be created using the custom or import feature, but I am unsure how to use those features or where to find any commands to import.
Has anyone created any?  Are they sharing with the public?

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
