### ISSUE TITLE
Meshing shortkeys with imacros

### ISSUE THREAD

**Issue by 912REKT** [mikecrittenden/shortkeys#228]
Hi
Currently, I'm using shortkeys v2.2.7 with chrome and windows 10.
The main reason I use shortkeys is to quickly access my imacro bookmarks which I use for work. For some reason though, shortkeys no longer works to open the imacro bookmarks. I don't know exactly when this problem first occured (sometime in the past few months). I'm not a programmer so I don't really know how to code much more than basic macros. If there is a way to revert back to a previous version of shortkeys or an update that could fix this, please let me know. Thanks!

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
