### ISSUE TITLE
Can't execute bookmarklets 

### ISSUE THREAD

**Issue by wall-of-sleep** [mikecrittenden/shortkeys#230]
Since the last Chrome update my bookmarklets appear to have stopped working. Regular bookmarks work and all bookmarklets still execute properly when triggered by clicking. Console shows this error associated with the extension:

Unchecked runtime.lastError while running tabs.update: JavaScript URLs are not allowed in chrome.tabs.update. Use chrome.tabs.executeScript instead.
    at Object.callback (<URL>)

**Comment by BlacKHeaDSg1** [comment]
Yea, this is an issue from December. It is useless add-on until they (or if) fix this problem. https://github.com/mikecrittenden/shortkeys/issues/221

**Comment by JohnDickson5** [comment]
Can you select "Run JavaScript" from the Behavior list and copy-paste the bookmarklet url into the "Javascript code to run" box? This worked for me.

**Comment by JohnDickson5** [comment]
Credit should go to the admin of the [Kantu](https://a9t9.com/kantu) support forums -- I didn't even realize it was a problem with all bookmarklets until I posted there.

**Comment by VancouverJohn** [comment]
JohnDickson5, thank you for sharing your solution.  It will save me many hours of work.

**Comment by mightybs** [comment]
What I discovered today is that this doesn't appear to be working for the "Open bookmark/bookmarkelt in current tab option"

<img width="322" alt="Screenshot 2019-07-22 13 20 33" src="https://user-images.githubusercontent.com/157826/61655124-84c97800-ac83-11e9-8a19-b481d1e30bdb.png">

The other options for opening a bookmarklet are working.

In this case I decided to take the bookmarklet javascript and make my shortcut run the Javascript instead.

Disappointing, but workable for now.

**Comment by mikecrittenden** [comment]
Anyone still having this issue with the latest version (3.0.1)?

**Comment by VancouverJohn** [comment]
I just checked and although I can execute the bookmarklets by clicking them directly, I can't seem to trigger them from shortkeys.

For a while I tried pasting the Javascript straight into shortkeys but that doesn't seem to work either anymore.

**Comment by mikecrittenden** [comment]
The fix for this will be included in the next release.
