### ISSUE TITLE
Tab command not working on Ubuntu Chrome

### ISSUE THREAD

**Issue by kleinjm** [mikecrittenden/shortkeys#232]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome 71.0.3578.98

* Operating System and version:

## Steps to Reproduce (for bugs)

1.
![image](https://user-images.githubusercontent.com/2565158/50944762-b7d2b980-145f-11e9-92d8-6966f20c49d9.png)
The last 3 shortcuts that all involve tabs do not work
2.
3.
4.

**Comment by mikecrittenden** [comment]
Closing some old issues, feel free to comment if this is still an issue.
