### ISSUE TITLE
Where can i find my SETTING location  ?

### ISSUE THREAD

**Issue by l0v3rd0** [mikecrittenden/shortkeys#233]
I am trying to edit a shortcut  i have in SHORTKEYS that run a javascript code without opening the OPTIONS bottom in google chrome but i could not find where the my stored data 
I searched for the extension location and i have founded 
AppData\Local\Google\Chrome\User Data\Default\Extensions\logpjaacgmcbpdkdchjiaagddngobkck\2.2.7_0

But where my settings goes ? i want to add another way to edit them

**Comment by csj3126** [comment]
Hi, I'm having the same problem. I need to be able to import the shortkey options I've customized from a command line automatically with a  script and not have to open the browser and configure the extension every time. I've searched my Ubuntu Linux box thoroughly and can't find the file :( Please help ASAP! Thank you :) Great extension!

**Comment by mikecrittenden** [comment]
Short answer: I have no idea where Chrome stores these things. If anyone finds it, feel free to respond.
