### ISSUE TITLE
disrupting calendar.google.com

### ISSUE THREAD

**Issue by comodh** [mikecrittenden/shortkeys#234]
I added Del to close the current tab. it works fine in all websites but in calendar.google.com when I clicked an event and them pressed Del, the event would be deleted and after adding the shortcut _t deleted the even but also closes the calendar tab as if I clicked Del twice!
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System and version: win10 pro version 1809 build 17763.253

## Expected Behavior

I added Del to close the current tab. it works fine in all websites but in calendar.google.com when I clicked an event and them pressed Del, the event would be deleted and after adding the shortcut _t deleted the even but also closes the calendar tab as if I clicked Del twice! it should only delete the event and that's it.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Weird stuff like this can happen when you use a shortcut which a site you commonly use is already using. There's not much that Shortkeys can do about this.
