### ISSUE TITLE
Run Javascript behavior won't activate within frames

### ISSUE THREAD

**Issue by JohnDickson5** [mikecrittenden/shortkeys#236]
I use Shortkeys primarily to run Kantu macros on a web application that uses multiple frames. While activating Bookmarks works within these frames, and Run Javascript will work if the cursor is outside of the frames, Run Javascript within a frame is not working. I'm been using the site https://a9t9.com/kantu/demo/iframes for testing. 

* Shortkeys version: Version 2.2.7
* Browser name and version: Chrome Version 72.0.3626.81 (Official Build) (64-bit)
* Operating System and version: Windows 10 version 1709

**Comment by mikecrittenden** [comment]
Yeah, it gets really hairy if we try to inject JS into iframes. I'm not sure of a way to safely do that. Because of the complexity and the fact that this is such an edge case, I'm closing this issue, but feel free to comment back if someone thinks this is an important issue to solve.

**Comment by non-bin** [comment]
I would like this too. To be able to speed up videos I use this:
<details>
  <summary>Code</summary>
  
  ```javascript
  if (!('customSpeedDisplay' in window)) {
	  customSpeedDisplay = document.createElement('CENTER');
	  customSpeedDisplay.appendChild(document.createTextNode('No video tags found'));
	  customSpeedDisplay.style = `
      position: fixed;
      top: 50px;
	  left: 50%;
	  transform: translateX(-50%);
      background: white;
      font-size: medium;
      z-index: 99999;
      padding: 2px;
      border-radius: 3px;`;
  
	  document.body.appendChild(customSpeedDisplay);
	  customSpeedTimeout = ''
  }
  
  document.querySelector('video').playbackRate -= 0.5;
  console.log('Video speed: ' + document.querySelector('video').playbackRate);
  
  customSpeedDisplay.innerText = 'Video speed: ' + document.querySelector('video').playbackRate;
  customSpeedDisplay.style.display = '';
  clearTimeout(customSpeedTimeout);
  
  customSpeedTimeout = setTimeout(() => {
	  customSpeedDisplay.style.display = 'none';
  }, 1500);
  ```
  
</details>

but it doesn't work for things like embedded youtube videos
