### ISSUE TITLE
Soft scrolling down feature

### ISSUE THREAD

**Issue by YvesCjl** [mikecrittenden/shortkeys#238]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome 72.0.3626.119
* Operating System and version: Windows

## Expected Behavior

Is it possible to implement softly scrolling down? It's supported in chrome inner implement( when pressing page down(up) ). I think it will look much better than simply modifying current position.

## Current Behavior

A little bit stiff when scrolling down.

## Steps to Reproduce (for bugs)

1. modify some key to "scroll down more"
2. trigger the key

**Comment by mikecrittenden** [comment]
Looks like we can do something like:

```
window.scrollBy({
  top: 100,
  left: 100,
  behavior: 'smooth'
});
```

Maybe a checkbox on all of the scrolling actions for "Smooth scrolling?" would be a good solution.

**Comment by mikecrittenden** [comment]
Pushed a fix for this. It'll be included in the next release. Thanks for the suggestion!

**Comment by gkop** [comment]
Thanks for the great plugin! I observe in Firefox 78 ESR (on a fresh Debian Bullseye install :roll_eyes: ) and Shortkeys 4.0.2, that the Scroll and Scroll More actions are _not_ soft. Would you welcome a contribution to make them soft?

**Comment by mikecrittenden** [comment]
There should be a checkbox to enable smooth scrolling tucked away in the expandable settings box. Do you see that?

**Comment by gkop** [comment]
Indeed, it works beautifully. Thanks Mike!
