### ISSUE TITLE
As of the latest version of firefox, your extension no longer works.

### ISSUE THREAD

**Issue by nrsrymj** [mikecrittenden/shortkeys#240]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox 67.0b5
* Operating System and version: Microsoft Windows 1

## Expected Behavior
Keyboard shortcuts should work.

## Current Behavior
They do not

## Steps to Reproduce (for bugs)
Use any preset keyboard shortcut. Does not work

**Comment by mikecrittenden** [comment]
Latest version may fix it (I'm not a Firefox user, and that addon is maintained by someone else). https://github.com/mikecrittenden/shortkeys/releases
