### ISSUE TITLE
No "Keyboard Shortcuts" settings in Chrome 70

### ISSUE THREAD

**Issue by mstarodub** [mikecrittenden/shortkeys#242]
Environment:
* Browser name and version: Chromium 70
* Operating System and version: Ubuntu 16.04

The FAQ and README mentions a "Keyboard Shortcuts" settings page which should be accessible in chrome://extensions and "scrolling to the bottom, then clicking Keyboard Shortcuts" or "entering chrome://extensions/configureCommands onto the address bar". 

Neither gives me any setting where I'm able to configure Chrome's built in shortcuts, only the ones for extensions I installed. Am I missing something?

**Comment by f4Andrew7** [comment]
next to the blue search bar in the extensions page there should be three lines. if you click that there should be a menu coming out of the side where you can find keyboard shortcuts.

**Comment by mstarodub** [comment]
@f4Andrew7 Yes, there is. However, in that menu, there does not appear to be any option to change shortcuts unrelated to extensions for me.

Can you please post a screenshot showing how that menu looks for you, along with the version of Chrom(ium) you're using?

**Comment by trihedral** [comment]
For me, it works to go to chrome://extensions/shortcuts and scroll down to the "Shortkeys (Custom Keyboard Shortcuts)" section.  There you can enter your custom shortcuts so they work on the new tab page, etc. 
(Chromium 74, Ubuntu 18.04)
