### ISSUE TITLE
Close other tabs STOPPED working today

### ISSUE THREAD

**Issue by Cajundragon** [mikecrittenden/shortkeys#244]
Been using a alt-w to activate 'Close other tabs'. Been working fine for a year. Stopped working now. Rebooted. Removed and re-installed extension. Not sure wtf is going on. (the keyboard is working).

System:
 Mint Linux 17.3 Rosa
 Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by mikecrittenden** [comment]
I think this should be fixed now but comment back if not.
