### ISSUE TITLE
Feature Requests: Open As Pop-up, Dev Tools, Shortcut Chaining

### ISSUE THREAD

**Issue by alivefromupstairs** [mikecrittenden/shortkeys#248]
- Add dev tools and open as pop-up as shortcuts (similar to this [extension](https://chrome.google.com/webstore/detail/open-as-popup/ncppfjladdkdaemaghochfikpmghbcpc?hl=en))
- Shortcut chaining. I would like to open dev tools before opening tab as a pop-up because it won't let me dock the dev tools otherwise.
Thank you.

**Comment by mikecrittenden** [comment]
No plans to support these, but I'd review PRs if anyone is interested.
