### ISSUE TITLE
Feature Request: move tab all the way to the left / right

### ISSUE THREAD

**Issue by alon91** [mikecrittenden/shortkeys#250]
**Current behavior**: Shortkeys offers two very useful shortcuts to relocate the active tab one over to the left / right:

* TABS: Move tab to the left
* TABS: Move tab to the right

**Feature request**: introduce a new shortcut that moves the active tab so it becomes the very first (left-most) or very last (right-most) tab. I currently accomplish this by repeatedly activating the existing shortcuts -- this works ok but is tedious, especially when there are many open tabs to move across. This is available in extensions like [Keyboard Shortcuts to Reorder Tabs](https://chrome.google.com/webstore/detail/keyboard-shortcuts-to-reo/moigagbiaanpboaflikhdhgdfiifdodd?hl=en).

(I love Shortkeys -- thanks for this amazing extension!!)

![image](https://user-images.githubusercontent.com/35006176/57975095-2a0c5b00-7978-11e9-9a45-fd27d154c5b4.png)

**Comment by alon91** [comment]
Woah!! I see the new code and pull request. What is the path for this feature to make it into the extension? I see that the extension was last updated in March 2019.

Thank you for looking into this!

**Comment by mikecrittenden** [comment]
Sorry for the long hiatus. I'm back around and I'll get this merged in and released ASAP.

**Comment by mikecrittenden** [comment]
Fixed and will be included in the next release. Thanks for the idea!
