### ISSUE TITLE
Feature Request: Open Chrome OS Apps

### ISSUE THREAD

**Issue by Mario253** [mikecrittenden/shortkeys#255]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome 74
* Operating System and version: Chrome OS 74

## Expected Behavior

This could probably be implemented in a separate Chrome OS app, and it may be overstepping CrOS's restrictions, but I would like to be able to activate an app (specifically, a Crostini app- Yakuake) using a keyboard shortcut. 
## Current Behavior

Right now, this extension only affects Chrome tabs, not the OS itself.
## Steps to Reproduce (for bugs)

N/A

**Comment by Sergej-Popov** [comment]
Hey @Mario253, give me a favour, can you build and test locally: #257 ? It should give you wat you want.
I've tested in on Win10, but don't have a ChromeOS to test.
