### ISSUE TITLE
Synced Run Javascript shortcut requires save and reload

### ISSUE THREAD

**Issue by tylercal** [mikecrittenden/shortkeys#258]
## Your Environment
Behavior has been observed in previous versions of shortkeys and chrome
* Shortkeys version: 2.2.7
* Browser name and version: Version 76.0.3809.87 (Official Build) (64-bit)
* Operating System and version: Windows 10, macOS

## Expected Behavior
I make an update to or add a new shortkey for "Run Javascript" on one browser and click Save. When I open a new tab on another browser, the new shortcut or changes are reflected on the new browser.

## Current Behavior
In order to make synced changes effective, I must open the modified or new shortcut on each browser, click save there, then reload the page I wish to use the shortcut in.

May be related to #168

**Comment by mikecrittenden** [comment]
Lots of updates have been put into the latest version (v3.0.0) and lots of these older issues are no longer current, so I'm closing this issue but feel free to comment back if it's still an issue.
