### ISSUE TITLE
Why 1,2 does not work to move to the previous/next tab?

### ISSUE THREAD

**Issue by worldor** [mikecrittenden/shortkeys#259]
Hello

Why 1,2 does not work to move to the previous/next tab?

I want them to be active when there is not focus in text forms.

thanks!

**Comment by mikecrittenden** [comment]
Can you provide more info? I'm not sure what you'er asking exactly.

**Comment by worldor** [comment]
why is this closed please?

**Comment by mikecrittenden** [comment]
@worldor can you respond to the previous question?

**Comment by worldor** [comment]
Yes, sorry I did not get the notification of the previous messages.

I set up the keys 1 and 2 to focus the previous/next tab but they do not work. I need them to work only when there is no IBeam cursor inside a text field in which case the keys should just type the numbers 1 or 2.

**Comment by mikecrittenden** [comment]
Those still work fine for me. See screenshot:

![image](https://user-images.githubusercontent.com/32261/71624029-75ddde80-2bae-11ea-8e34-84207c02fa79.png)

Have you tried re-saving your Shortkeys settings? Or possibly disabling and re-enabling the extension?

**Comment by mikecrittenden** [comment]
@worldor pinging you by name just in case you don't get notifications for thread replies.

**Comment by mikecrittenden** [comment]
Closing for lack of ability to reproduce. Please let me know if you have any more info/help reproducing.
