### ISSUE TITLE
shortcut for 'hard reload'

### ISSUE THREAD

**Issue by Krysztokowski** [mikecrittenden/shortkeys#261]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome Version 71.0.3578.98 (Offizieller Build) (64-Bit)
* Operating System and version: Ubuntu 19.04 LTS

## Expected Behavior (enhancement)

I would love to set shortcut for a hard reload (currently Ctrl + Shift + R)
-> clearing cache and reload the page

## Current Behavior
nothing

## Steps to Reproduce (for bugs)
none

**Comment by mikecrittenden** [comment]
This will be included in the next version.
