### ISSUE TITLE
Feature Request: key to play/pause videos on all video playback websites

### ISSUE THREAD

**Issue by gifthubbro** [mikecrittenden/shortkeys#262]
## Expected Behavior
I want to permanently make space play/pause videos even if I didn't click the play/pause button beforehand
In youtube/vimeo/dailymotion website they support this, pressing  space plays/pauses a videos even if you didn't click the video Play/pause function with your mouse beforehand to make it active

## Current Behavior
For certain websites, such as twitch , I have to click the video play/pause button before it responds to the play/pause space key. any method to make it respond to space to play/pause the video instantly, without having to click the play/pause first, in these certain websites that don't respond to it ?
## Steps to Reproduce (for bugs)
Here's a gif example – first I pressed “space” and it moved lower down the screen. To remedy this I had to click the play/pause button on the website and then “space” worked to play/pause, I want to permanently make space play/pause videos even if I didn't click the play/pause button beforehand https://i.imgur.com/lZchpxu.gifv
1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
I don't believe there's a global way to make this happen. I think it'd have to be dependent on how each website plays its videos, so I don't think it's something Shortkeys can add general support for.
