### ISSUE TITLE
"Previous Tab" and "Next Tab" do not work in page source tabs

### ISSUE THREAD

**Issue by nirno** [mikecrittenden/shortkeys#265]
## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Firefox Quantum 68.0.2 (64-bit)
* Operating System and version: Arch Linux (rolling), upgraded 2019-07-21

## Steps to Reproduce (for bugs)

1. Configure "alt+left" for "Previous tab", "alt+right" for "Next tab". 
2. Go to"https://en.wikipedia.org/".
3. Choose "Tools->Web Developer->Page Source".  A new tab opens.
4. Press Alt-Left.

## Expected Behavior

The previous tab (Wikipedia, rendered) activates again.

## Current Behavior

Nothing happens.  Default shortcuts (Ctrl-PgUp, Ctrl-PgDn) work correctly.  In other tabs, Alt-Left and Alt-Right work as expected.

**Comment by user8446** [comment]
It's a limitation in chrome. You won't be able to use shortcuts in a new tab page, and chrome settings page, etc.
