### ISSUE TITLE
incompatibility with another extension

### ISSUE THREAD

**Issue by ghost** [mikecrittenden/shortkeys#266]
with "Keyboard Savior Xtreme" enabled the Shortkeys dont work, have something to do to make compatible?

**Comment by mikecrittenden** [comment]
I think that would be something that the other extension would have to do, rather than something I could fix on my end.

**Comment by Mike-Reddick** [comment]
@mikecrittenden please, is possible add to Shortkeys an setting to do the same thing than "Keyboard Savior Xtreme" addon? I think it is very related with the Shortkeys. This new optional setting is very simple, just disable all custom shortcuts of all sites. Thanks
