### ISSUE TITLE
Extension should request permission to "clipboardRead" for execCommand('paste')

### ISSUE THREAD

**Issue by jrfoell** [mikecrittenden/shortkeys#267]
I've implemented Super-X/C/V (Cut/Copy/Paste) using Shortkeys and only paste is currently not working. I think declaring the "clipboardRead" permission for your extension _might_ solve the issue. https://developer.chrome.com/extensions/declare_permissions

## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Chrome 77
* Operating System and version: Ubuntu 18.04

Export:
```
[{"action":"javascript","activeInInputs":true,"blacklist":false,"code":"try {  \n    var successful = document.execCommand('paste');  \n    var msg = successful ? 'successful' : 'unsuccessful';  \n    console.log('Paste command was ' + msg);  \n} catch(err) {  \n    console.log('Oops, unable to paste');  \n}","customName":"Paste","exported":true,"key":"command+v","open":true,"sites":"*","sitesArray":[]}]
```

## Expected Behavior
1. Text is pasted
2. Message in the console log:
> Paste command was unsuccessful

## Current Behavior
1. Text is not pasted
2. Message in the console log:
> Paste command was successful

## Steps to Reproduce (for bugs)
1. Install Shortkeys extension for Chrome
2. Import "Paste" action from above - change keybinding if needed.
3. Visit a page with a textarea field (a github issue works well)
4. Open Chrome's Developer Tools Console
4. Write some text, select and copy it to the clipboard.
5. Observe "Paste command was unsuccessful" in the console (and nothing pasted)

**Comment by mikecrittenden** [comment]
See https://github.com/mikecrittenden/shortkeys/issues/33

I'd prefer to stay away from supporting OS-level interactions like copying and pasting since there are much better solutions for that.
