### ISSUE TITLE
Shortkeys icon on macOS Dark Mode

### ISSUE THREAD

**Issue by Acidham** [mikecrittenden/shortkeys#268]
Icon for shortkeys not visible in dark mode

## Your Environment
* Shortkeys version: 2.27
* Browser name and version: Chromium 79
* Operating System and version: macOS 10.14.6

## Expected Behavior
Once Shotkeys was installed I expect to see it in next to all the other extensions but it seems that I am getting an empty space there due to dark shortkeys icon. 

Please add the ability to invert the dark icon to white or any other color.

**Comment by mikecrittenden** [comment]
The icon has been updated now in the most recent version to a pair of blue shorts ("short"keys - get it? I know, it's bad). Here's a screenshot:

![2019-12-23 at 11 35 AM](https://user-images.githubusercontent.com/32261/71369311-56283400-2578-11ea-9580-34214c92530a.png)
