### ISSUE TITLE
As a user I'd like to be able to load shortkeys configuration shortcuts (import them) to the extension without having to go thru the browser

### ISSUE THREAD

**Issue by csj3126** [mikecrittenden/shortkeys#269]
## Description:
As a user I'd like to be able to load shortkeys configuration shortcuts (import them) to the extension without having to go thru the browser. I'd like the ability to write a script and import my configs. 

## Your Environment:

* Shortkeys version: 2.2.7
* Browser name and version: Chromium, v77.0.3865.90 (Official Build)
* Operating System and version: Ubuntu Linux Server 18.04

## Expected Behavior
 Not a bug

As a user I'd like to be able to load shortkeys configuration shortcuts (import them) to the extension without having to go thru the browser. I'd like the ability to write a script and import my configs. 

## Current Behavior
 Not a bug

Right now there is no known way to import a configured config file to shortkeys from the command line.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
This isn't something I'm willing to support, but note that there is a "Sync to other devices" button per-shortcut, in the "Settings" section of each shortcut, if that solves your problem.
