### ISSUE TITLE
As a user I'd like to be able to export my config file as a file so it may be imported later as a file vs copy paste

### ISSUE THREAD

**Issue by csj3126** [mikecrittenden/shortkeys#270]
## Description:
As a user I'd like to be able to export my config file as a file so it may be imported later as a file vs copy paste. Export button in "Export" tab which will download a json file.

## Your Environment:

* Shortkeys version: 2.2.7
* Browser name and version: Chromium, v77.0.3865.90 (Official Build)
* Operating System and version: Ubuntu Linux Server 18.04

## Expected Behavior
 Not a bug

As a user I'd like to be able to export my config file as a file so it may be imported later as a file vs copy paste. Export button in "Export" tab which will download a json file.

## Current Behavior
 Not a bug

Currently there is no export to a json file method

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
This is a reasonable request but I don't think many people would use it, especially when syncing is built in to the extension, so I'm not sure that it's worth the complexity and effort.
