### ISSUE TITLE
Is there a way to enter a word that commands an action? 

### ISSUE THREAD

**Issue by srasc** [mikecrittenden/shortkeys#271]
Is there a way to enter a word that commands an action? (For example, typing in "go" and that prompting a bookmark to get opened in a new tab.

**Comment by mikecrittenden** [comment]
Sure, just put a space between the letter. So you'd use `g o` instead of `go`. Screenshot which I just tested:

![2019-12-23 at 11 38 AM](https://user-images.githubusercontent.com/32261/71369413-bd45e880-2578-11ea-81b3-e87ffc9fed52.png)
