### ISSUE TITLE
Introduce support for the "insert" special key

### ISSUE THREAD

**Issue by mlewand** [mikecrittenden/shortkeys#273]
It would be great to also add support for the `insert` key.

There are already `del`, `home`, `end`, `pageup`, `pagedown` - the only missing player is `insert`.

My use case is that I'm using some finance-related app where I'd like to make a hotkey for adding expenses to something like `ctrl+insert`. Tried it and it didn't work.

## Your Environment

* Shortkeys version: 2.2.7
* Browser name and version: Chrome/77.0.3865.120
* Operating System and version: Windows NT 10.0; Win64; x64

## Expected Behavior

I'd like `ctrl+insert` to handle a insert and a control keystroke.

![image](https://user-images.githubusercontent.com/5353898/67161119-bf60b080-f357-11e9-8e48-3efb71b2beb9.png)

`insert` key seems not to be supported at this time.

Once it's supported the docs should also list new `insert` key too https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#supported-keyboard-shortcuts

## Current Behavior

Key is not handled.

## Steps to Reproduce (for bugs)

1. Open Chrome with the extension installed.
2. Go to extension options.
3. Add a new hotkey.
4. Set Keyboard shortcut to `ctrl+insert`.
1. Set behavior to e.g. "New tab".
1. Save.
1. Open a new tab and navigate to any website.
1. Once loaded press `ctrl+insert`.

**Comment by mikecrittenden** [comment]
I'm afraid I can't test or support this one since I use a Macbook Pro keyboard which has no insert key. If we do support it, it would come by default from Mousetrap, the library which we are using for key bindings. Feel free to file the issue there if you'd like: https://github.com/ccampbell/mousetrap/issues?utf8=%E2%9C%93&q=insert
