### ISSUE TITLE
"Behavior" selector just shows black square.

### ISSUE THREAD

**Issue by Lunatic3k** [mikecrittenden/shortkeys#275]
Trying to set any hotkey in extension, and getting black square after clicking "Behaviour" dropdown menu. It once flashed with actual options, but only for one moment. I tried changing/resetting Chromes theme, didn't help.

## Your Environment
Shortkeys version: 2.2.7
Browser name and version: Chrome/78.0.3904.70
Operating System and version: Windows 10.0 Pro; x64

## Expected Behavior
1. Click on Behavior
2. Show actual options

## Current Behavior
1. Click on Behavior
2. Shows up black square

![4MEu58u](https://user-images.githubusercontent.com/7556593/67765599-415b8280-fa98-11e9-8f49-4237257e3c0b.png)

**Comment by periurium** [comment]
Also having this issue on multiple devices

**Comment by freunx** [comment]
I had the same issue.
Here are 2 possible solutions:
1. In the behavior field try to write the first initials of your behavior, for example: RU for run javascript.
2. Export all of your shortcuts, and then try to re-import them(if you have them on multiple devices)

It seems to be related to chrome's newest upgrade.

**Comment by user8446** [comment]
@mikecrittenden  
Having the same issue. This seems to be throughout the extension settings. The help links, the bookmarks window, and the websites activation settings

**Comment by ambrt** [comment]
Same here
![dropdownbug](https://user-images.githubusercontent.com/10456131/68545277-c4030c80-03cb-11ea-9fdf-574699bffa37.png)

I'm not on Beta (as @user8446 ). i'm on today"'s '"Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by DJQuadRocks** [comment]
Same issue here.

**Comment by ADrifter** [comment]
你可以用方向键来控制

**Comment by ambrt** [comment]
I'm on 79.0.3945.79 chrome now, and the issue seems to be gone. But i also changed display screen so i'm not sure if others have it solved.

**Comment by mikecrittenden** [comment]
HI all, I pushed up v3 which is a bit of an overhaul/updating of the extension code after a long hiatus. Feel free to see if that fixes the issue for you: https://github.com/mikecrittenden/shortkeys/releases/tag/v3.0.0

It'll hit the webstore next week after some more testing.

**Comment by mikecrittenden** [comment]
v3 is on the webstore now so I am closing this as fixed, but feel free to reopen if people are still seeing the issue.
