### ISSUE TITLE
Is it possible to add support to keys '[' and ']'? Thanks! 

### ISSUE THREAD

**Issue by Leotrinos** [mikecrittenden/shortkeys#277]
## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by mikecrittenden** [comment]
Those keys are supported. Here's an example, showing using them for shortcuts:

![2019-12-23 at 11 31 AM](https://user-images.githubusercontent.com/32261/71369115-c2566800-2577-11ea-9375-3a195a60a46f.png)
