### ISSUE TITLE
How to disable zoom? (ctrl++)?

### ISSUE THREAD

**Issue by ThorAtlas** [mikecrittenden/shortkeys#278]
How does one disable the zoom function in chrome? I tried using ctrl++, do nothing. But that does not seem to work. Is there a way to make the extension read the + as a symbol and not as a function?

## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by jacceko** [comment]
I am looking for such solution too

**Comment by mikecrittenden** [comment]
Sadly it appears Chrome's extension API doesn't support disabling these specific key combinations, presumably for accessibility reasons.
