### ISSUE TITLE
Feature request: open image in new tab keyboard shortcut

### ISSUE THREAD

**Issue by HolmesMalone** [mikecrittenden/shortkeys#280]
FF and chrome.

**Comment by mikecrittenden** [comment]
How would it know which image to open? The one you're currently hovering over or something like that? That seems a little sketchy and in the weeds for a general purpose keyboard shortcut extension like this one, so I'm going to close this issue, but feel free to reply back if you disagree.

Also note https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab?hl=en supports lots of those types of things.
