### ISSUE TITLE
Can this tool be used to type in specific text?

### ISSUE THREAD

**Issue by hamayounCS** [mikecrittenden/shortkeys#281]
Can this tool be used to type in specific text?  Let's say there's some text which I am typing into an input box frequently, can this tool be used to create a shortcut to do that?

**Comment by mikecrittenden** [comment]
In theory it could, but something like https://chrome.google.com/webstore/detail/textexpander-for-chrome/mmfhhfjhpadoefoaahomoakamjcfcoil?hl=en would be a much better tool for that.
