### ISSUE TITLE
key case sensitivity and double click is not working

### ISSUE THREAD

**Issue by yondonjamts1** [mikecrittenden/shortkeys#282]
## Your Environment
* Shortkeys version: 2.2.7
* Browser name and version: Google Chrome  78.0.3904.108 64bit
* Operating System and version: Ubuntu 18.04 64bit

## Expected Behavior
wanted to double click key and case sensitive
pressing 'double g' === 'gg' -> go to top of the page *like VIM hotkey
pressing 'uppercase g' === 'G' -> go to bottom of the page *like VIM hotkey

## Current Behavior
When I clicked 'lowercase g' === 'g' -> single time it goes to bottom of the page.

**Comment by mikecrittenden** [comment]
Use `g g` instead of `gg` (it needs a space to see that as 2 separate keys pressed one after the other.

Try `shift+g` instead of `G` and see if that does it for you.

**Comment by yondonjamts1** [comment]
Oh, I see. Thanks a lot :) Now it's way better web browsing experience :smile:
