### ISSUE TITLE
This extension doesn't seem to work with macs. Is that the case?

### ISSUE THREAD

**Issue by coltrane58** [mikecrittenden/shortkeys#283]
## Your Environment

* Shortkeys version:
* Browser name and version:
* Operating System and version:

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by coltrane58** [comment]
I am trying to install this extension on a Brave browser and it doesn't seem to take keystrokes from a mac. Is it made to work with macs?

**Comment by mikecrittenden** [comment]
It works fine on Macs in general but I can't vouch for it in Brave browser. Having never used Brave, I can't officially support it, but feel free to comment back if you have specific issues you are able to identify.
