### ISSUE TITLE
Create a folder in Bookmarks

### ISSUE THREAD

**Issue by sterbalr** [mikecrittenden/shortkeys#285]
I'm looking for a keyboard shortcut that will create a folder in the bookmarks file.

I have a set of 0-9 to Z folder and want to create subfolders AD, AE, AM, etc under A and so on.

I looked for an extension, and recommendations for another one that would do this would be welcome.

**Comment by mikecrittenden** [comment]
This seems a little too obscure for Shortkeys to support, and I'm not sure of any other extensions that do anything like this.
