### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by lss662** [mikecrittenden/shortkeys#287]
Chrome has disabled shortkeys due to new permissions. The permissions are 

* Manage your apps, extensions, and themes

These are not described on https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#why-are-all-these-permissions-required

Shortkeys version: 3.0.2
Chrome Version 79.0.3945.88  for windows
OS: Windows 10

**Comment by mikecrittenden** [comment]
Thanks, good point. I added info here: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#manage-your-apps-extensions-and-themes

For the record, here's the change that added that permission: https://github.com/mikecrittenden/shortkeys/pull/257/files
