### ISSUE TITLE
Update Ups!

### ISSUE THREAD

**Issue by Patuta** [mikecrittenden/shortkeys#289]
Since update on 28th Dec shortkeys have stopped working. Could it be caused by Firefox not granting permission? Though all boxes seemed to be ticked in the addons manager. What should I do?

**Comment by Patuta** [comment]
The catch: I wouldn't workt till I switched the bind to a pre-existing shortkey, saved it, switched it back again and refreshed the tab. Now it's back on.

**Comment by mikecrittenden** [comment]
Hmmmmm. Not sure what to do here. Should this be closed or are you thinking you found a bug?

**Comment by Patuta** [comment]
Issue is solved. But I think it's notable that shortkeys initially did not work atfer updating and a workaround was needed..
