### ISSUE TITLE
Can't access options

### ISSUE THREAD

**Issue by mabloom** [mikecrittenden/shortkeys#292]
I installed this extension with the hope of being able to use keys such as control-F
in firefox the way I can in chrome, but am unable to get to the point of even accessing the extension's options.

Installation just tells me what permissions are _needed_, but does not ask me to 
_enable_ them.  Firefox claims the extension is installed, but unlike some other extensions, there is no "Options" button to click, only Disable and Uninstall buttons.

Clicking the "Documentation", "Support", or "Code" links brings up a "Blocked by Content Security Policy" message.

If I click Disable, when I then click Enable, the text "{{alert.msg}}" appears momentarily and immediately disappears.

I assume there is some sort of permissions problem.  Is there perhaps something I can set in about:config to get past it?

This is on a Samsung tablet running Android 9 over linux kernel 4.4.

**Comment by mikecrittenden** [comment]
I have no good way of testing Firefox on Android unfortunately so I can't officially support it. I suppose I'll close this issue just for lack of options, but if anyone sees this and has suggestions/thoughts, please do respond.

**Comment by mabloom** [comment]
Actually, there is a good way for you to test Firefox on Android, using "bluestacks", a free Android "emulator".  (I put "emulator" in quotes because he program actually contains a complete Android system, runs under any Windows version ≥ XP and emulates  is the ARM CPU's instruction set when it needs to, running Android apps faster than they would run on most phones or tablets). It's downloadable from bluestacks.com.  

The first time you run it, you'd need to install Firefox, which you can do by running the Google "repository app" called "Play Store", entering "Firefox" in its search bar,  and then clicking on the Firefox icon.

If you are using Linux rather than Windows, there are a number of options.  You could install a basic Android (via Synaptic, or your system's equivalent), which is analogous to installing Gnome or KDE, but it would probably be better to install one of the more complete (and sandboxed) systems out there (you can find them by googling "Android under Linux").'  

If you are using Windows, one final note: It's probably a good idea to set the switch that tells bluestacks to change the ABI mode explicitly to ARM for the benefit of apps that fail to bundle both the ARM and x86 versions of the  libraries they need.
