### ISSUE TITLE
Search Google for selected text stopped working

### ISSUE THREAD

**Issue by drguybh** [mikecrittenden/shortkeys#293]
I'm using the extension on Chrome OS (v 79) and shortcuts are working fine except "search google for selected text", which I had mapped to ctrl+alt+g. I tried adding the shortcut to Chrome's keyboard shortcuts settings, but ctrl+alt is flagged as an "invalid combination". I think the shortcut stopped working with the update to Chrome OS 79. Can you help?

**Comment by mikecrittenden** [comment]
See #291. This is already fixed but for some reason Google Web Store has the release set to "pending review" since like 2 weeks ago. Sorry about that. I'm not sure what's taking so long. Grab a new release from the releases page of this repo if you need it in the meantime.
