### ISSUE TITLE
Using cmd-left and cmd-right to switch tabs in Firefox

### ISSUE THREAD

**Issue by aguynamedben** [mikecrittenden/shortkeys#299]
I'm trying out Firefox (72.0.1) and can't get `cmd-left` and `cmd-right` to change tabs.

![image](https://user-images.githubusercontent.com/107841/72379965-4a3c1780-36c9-11ea-8931-ebe154bdd8ea.png)

After saving those settings and restarting Firefox, `cmd-left` and `cmd-right` still do Back/Forward, not Next Tab/Previous Tab. Any ideas? I also tried `command-left` and `command-right` and those didn't work either.

**Side note/rant:** Is there a good reason Firefox doesn't include these basic actions in the macOS menu? Chrome puts `Select Next Tab` and `Select Previous Tab` under the Tab menu (macOS menu bar). Then I use macOS `System Preferences -> Keyboard -> Shortcuts` to customize the shortcuts. It's crazy Firefox doesn't have basic settings for keyboard shortcuts.

**Comment by mikecrittenden** [comment]
Yeah, there are some core browser shortcuts that Shortkeys doesn't have the ability to override, just due to limitations in the extension API. cmd-left/right are 2 examples of those. Firefox addons just can't change that behavior sadly. :(

**Comment by aguynamedben** [comment]
Thanks for clarifying. I gave feedback to Firefox.
