### ISSUE TITLE
Setting to disable web sites custom shortcuts

### ISSUE THREAD

**Issue by Mike-Reddick** [mikecrittenden/shortkeys#302]
Please add an setting to disable (remove) all custom keyboard shortcuts of all sites. This can be optional, just a little checkbox.

Thanks!

**Comment by mikecrittenden** [comment]
I don't believe there's a reliable way to do that, since websites can implement their own keyboard shortcuts so many different ways. There's no way for Shortkeys to undo them after the fact that I'm aware of.
