### ISSUE TITLE
Firefox Add-on 'CanvasBlocker' Blocks Shortkeys

### ISSUE THREAD

**Issue by PseudoAnonymous** [mikecrittenden/shortkeys#303]
Firefox 72.0.1 (64bit)
Shortkeys 3.0.4
CanvasBlocker 1.0 ( https://github.com/kkapsner/CanvasBlocker/ )

Disabling CanvasBlocker meant my hotkey combos worked, so, I know that's the source of the problem.

However, disabling CanvasBlocker just to enable Shortkeys isn't a (long-term) solution for me - if I have to do without one of them then, unfortunately, it'll have to be Shortkeys (privacy/security trumps convenience).

I'm pretty sure it has to be resolvable though: it's bound to be related to one of the protected API features.

Would rather discuss this privately though - not keen on publishing my CanvasBlocker config. in public!

Thanks.

**Comment by mikecrittenden** [comment]
My gut reaction is to do nothing here, since I'm assuming the overlap of people who want to use both Shortkeys and Canvas Blocker is very small (maybe less than 10 people) and I'm hesitant to add extension-specific code to Shortkeys (i.e., write code specifically for Canvas Blocker users) just to support that handful of people, but I'll leave this open for a while in case anyone else wants to speak up and say it affects them as well. Or maybe there's a fix here that isn't quite as hacky as what I'm imagining.

**Comment by PseudoAnonymous** [comment]
Thanks for the reply (and the offer to leave it open).

I'm not sure you'd necessarily need to do anything in the first instance beyond helping me track down what the source of the problem is though. 

If it's a matter of Shortkeys making use of a particular API feature that I'd have to open up the World and its dog then, fine, sad though I'll be,, I'll just have to forego Shorkeys. 

But if it's just a matter of my having been overly restrictive with my settings, or of there being  a workaround I can implement, (or a simple whitelist exception I can make in the case of Shorkeys specifically) then that would be the ideal solution - it's just that, as I'm not the dev, I don't know how Shortkeys works at that level and don't know where to start investigating beyond randomly enabling API features (with potentially undesirable consequences as far as I'm concerned).

So, really, I was hoping you could help me work out where the problem lies rather than re-writing Shortkeys to accommodate me.

**Comment by mikecrittenden** [comment]
I'm unfortunately not really sure where I could help. My only suggestion is to check out the list of permissions that Shortkeys uses in the manifest.json file and see if any of those look like likely candidates that Canvas Blocker is blocking.
