### ISSUE TITLE
Shortkeys now a paid extension in the Chrome store??

### ISSUE THREAD

**Issue by user8446** [mikecrittenden/shortkeys#304]
I noticed that I was still on v3.0.3 and checked and I see this is now a paid extension in the Chrome store. No notice, documentation, nothing.
I have no problem paying for the auto-update convenience and to help support development but to switch mid-stream is not a good business practice. This also specifically penalizes Chrome users.
I would have donated more than the $1.99 anyway.
Thank you for the development but some type of documentation would be great.

**Comment by mikecrittenden** [comment]
Hi there. What type of documentation do you have in mind? Just a wiki page explaining why it's a paid extension now?

**Comment by user8446** [comment]
Hi Mike,

A small explanation on the extension page on the chrome store that explains to receive further bug fixes and improvements then users would have to pay. There are currently 96,957 users and I'm sure quite a few have no idea that they won't be automatically updated anymore.

That gives the users full honest disclosure and as well will probably bring more paying users to you instead of them all sitting at v3.0.3 forever.

**Comment by mikecrittenden** [comment]
> NOTE: Shortkeys is now a paid extension. If you haven't yet bought it, you will need to do so in order to continue to receive updates. 

How's that sound, for the extension page on the webstore?

**Comment by user8446** [comment]
Sounds good!

**Comment by mikecrittenden** [comment]
Cool, I updated the extension page. Note that it may take a while for the changes to appear because Google has to verify all this stuff before it gets published.

**Comment by sterbalr** [comment]
It should have a different name. Typically something like Shortkeys Pro.
