### ISSUE TITLE
Brave

### ISSUE THREAD

**Issue by coltrane58** [mikecrittenden/shortkeys#305]
Will Shortkeys (Custom Keyboard Shortcuts)work in the Brave browser? Want to know before I pay for it

**Comment by mikecrittenden** [comment]
Good question. I don't know anything about how extensions work for Brave. Want to grab a release from the releases page in this repo so you can try it without paying? https://github.com/mikecrittenden/shortkeys/releases

**Comment by coltrane58** [comment]
I don’t think the extension works on mac. I tried ctrl+5 and ctrl+cmd+5 for closing a tab and neither worked. I tried with Brave and Chrome on a mac running High Sierra.

Thanks for the help

**Comment by mikecrittenden** [comment]
It works on a Mac in general - I personally use a Mac and many other Shortkeys users do as well. Maybe needed to try some of the troubleshooting steps: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#None_of_my_shortcuts_are_working_Why_isnt_Shortkeys_doing_anything

Anyways, thanks for trying!

**Comment by coltrane58** [comment]
I’ll keep you updated. I’ll try not to be a bother. If I want to create a key combination using either the command or option keys how should it appear in the keystroke field? Cmd+alt+x or cmd+opt+x?

Thanks again.

**Comment by mikecrittenden** [comment]
We use https://craig.is/killing/mice for wrangling keyboard shortcuts, which says:

> You can substitute `option` for `alt`

**Comment by coltrane58** [comment]
Much thanks. I seems that your extension seems to work with Brave. I’ll purchase a copy. One of these days I’ll learn how to write an extension. I’m an ex-C++ developer with some java experience. Too bad I ditched my javascript books when I retired. 

 

Thanks again

 

john

**Comment by mikecrittenden** [comment]
Woohoo! Sure thing!
