### ISSUE TITLE
Print Selection only

### ISSUE THREAD

**Issue by sterbalr** [mikecrittenden/shortkeys#308]
It would be handy to have a print selection hotkey combination. Is that a possibility?

**Comment by mikecrittenden** [comment]
@sterbalr You mean you'd select some text and hit the hotkey and it would send only that text to the printer?

**Comment by mikecrittenden** [comment]
I'd be willing to review a PR for this if anyone wants to submit one, but I am not able to work on this myself. It seems like this will be a rarely used feature and the only way I can find to accomplish it would be via some pretty gross CSS hacks, such as: https://stackoverflow.com/questions/4373922/how-to-print-selected-div-instead-complete-page
