### ISSUE TITLE
Disabling shortcut isn't working

### ISSUE THREAD

**Issue by theinkera** [mikecrittenden/shortkeys#309]
I saved several shortcuts to be disabled and then I try them and they still work. I reload the page but they're not disabled

**Comment by mikecrittenden** [comment]
Unfortunately there are some shortcuts that browsers just don't allow you to disable. Here are the docs: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#Can_I_use_Shortkeys_to_disable_a_core_browser_shortcut
