### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SmogCop** [mikecrittenden/shortkeys#311]
Hello.  I purchased and installed ShortKeys ext for Chrome.  After installation, I attempted to disable several shortcuts.  After following instructions provided on https://www.addictivetips.com/web/disable-a-chrome-keyboard-shortcut/.

Following the instructions, I entered options.  Selected Add.  Entered ctrl+r (also d, j, k, e, s, q).  Scrolled down and selected "Do Nothing".  Then selected Save.

After restarting Chrome, I checked out if the key was disabled by opening Calendar and opening a new appointment.  I typed into the title, then pressed ctrl+r.  This should have resulted in nothing happening.  Instead a box opened up asking me if I wanted to reload the site.

I also attempted this on an outside website, MSN.com and had the same results.  Please advise what I may have done wrong.  Thank You.

**Comment by mikecrittenden** [comment]
Unfortunately there are some browser shortcuts that extensions do not have the power to override. I'm not positive but I'd bet there's a good chance ctrl+r is one of those.

Here are the docs on this: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#Can_I_use_Shortkeys_to_disable_a_core_browser_shortcut

**Comment by SmogCop** [comment]
Thank you for getting back to me. I suspected as much. ☹️.

Do you know of any way to disable the CTRL key on the keyboard?

Thank you.

**Comment by mikecrittenden** [comment]
I'm assuming you're on Windows? If so, I'd say to start with AutoHotKey which has a lot of power for things like that. That said, I'm not a Windows user so I can't speak from experience.

**Comment by mikecrittenden** [comment]
Closing the issue since I don't think Shortkeys can do anything here but feel free to respond back if needed.
