### ISSUE TITLE
It didn't work after i made a javascript on a site.

### ISSUE THREAD

**Issue by area111314** [mikecrittenden/shortkeys#314]
Hi Mike
Sorry for making an issue here.
I'm pretty newbie to Javascript, and I've made a javascript for a site.
After that Shortkeys is no longer work on that site anymore.
Here's my javascript's code
`document.documentElement.innerHTML = "";
GM_xmlhttpRequest({
    method : "GET",
    url : 'http://sitedomain/',
    onload : function(e) {
        var doc = inject(e.responseText);
        document.open();
        console.log(doc);
        document.write(doc);
        document.close();
    }
});`
Thank you for your time, and sorry again for my poor english too.

**Comment by mikecrittenden** [comment]
What is `GM_xmlhttpRequest`? Are you sure that's defined on the page?

**Comment by area111314** [comment]
Sorry I don't get it,but I guess the answer is yes?
since I can use function inject,which means it will only work when page is onload.
Here's my full code
[Greasyfork link](https://greasyfork.org/en/scripts/396508-edge-agar-io-script-v-1-0-0%E5%85%B7)
