### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by shaicoleman** [mikecrittenden/shortkeys#315]
Whenever the extension is loaded, it always displays in the developer console the following error:
```
contentscript.js:1 Uncaught (in promise) Error: Unexpected token u in JSON at position 0
    at A (contentscript.js:1)
```

Chrome v80 (Linux/Windows), tried disabling other extensions, but it didn't make a difference

**Comment by mikecrittenden** [comment]
Do you have any complicated Shortkeys commands (for example, with custom JS in them)?

**Comment by shaicoleman** [comment]
No, I just have the following shortcuts:
F1 - Go back
F2 - Go forward
F4 - Close tab

**Comment by mikecrittenden** [comment]
Weird....did you try re-saving your shortcuts?

**Comment by shaicoleman** [comment]
Deleting all shortcuts, exporting and reimporting them seemed to fixed the issue

**Comment by mikecrittenden** [comment]
Interesting. Alrighty then I suppose we can close this. It's concerning that this was able to occur but without any other reports and without a way to reproduce, I'm not sure anything can be done here.
