### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by GorillaG** [mikecrittenden/shortkeys#317]
Hey, im trying to use the feature for Tribal Wars but nothing happens when i press the button.

I tried using shortkeys for simple commands such as scroll to the bottom of the page and set the key H but still nothing happens. I have saved and reopened the browser and still nothing.

Could you help me out?

**Comment by mikecrittenden** [comment]
Hi there! In terms of troubleshooting steps, the only real steps to try are on this wiki link: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#None_of_my_shortcuts_are_working_Why_isnt_Shortkeys_doing_anything

**Comment by mikecrittenden** [comment]
Feel free to post a screenshot of your Shortkeys settings page if you'd like.
