### ISSUE TITLE
Search In Tab short cut is missing

### ISSUE THREAD

**Issue by sgandon** [mikecrittenden/shortkeys#318]
I'd like to be able with a short cut to do exactly what the menu "Search in tabs"  does using a shortcut. 
But is seems this option is not available in this extension.

**Comment by mikecrittenden** [comment]
Do you mean an extension called "Search in tabs"? Can you provide a link? I'm not sure what "Search in tabs" is exactly. (I can guess, based on the name, that it searches all your open tabs, but I'd like to see exactly what you're referring to)

**Comment by sgandon** [comment]
Nope this is a native Firefox menu when you have a lot of tabs.

<img width="1143" alt="Capture d’écran 2020-03-02 à 16 27 29" src="https://user-images.githubusercontent.com/783286/75690445-28134e80-5ca3-11ea-98d2-fb7b724a425b.png">

(sorry for the french screen shot)

**Comment by mikecrittenden** [comment]
Ah, I see! Interesting, I didn't know Firefox supported that.

That said, I do not see a way in the webextension API to trigger that programmatically unfortunately.
