### ISSUE TITLE
feature_request(shortcut): close all tabs, include current and pinned

### ISSUE THREAD

**Issue by Kristinita** [mikecrittenden/shortkeys#322]
### 1. Summary

It would be nice, if would be possible close all tabs, include current and pinned via hotkey.

### 2. Argumentation

I'm working in Firefox on several projects. For each I have a separate workplace.

For each workplace I have specific set of pinned tabs. Apart from these tabs I can use any other tabs in my work. I want to write scripts, that, in particular, close all tabs of first workplace, then open and pin tabs for new workplace.

Problem — I can't find any method for closing all pinned tabs, include current.

#### 3.1. Close All Tabs Button

Extension [**`Close All Tabs Button`**](https://addons.mozilla.org/en-US/firefox/addon/close-all-button/) can close pinned tabs. But it haven't shortcut. Repository of this extension is [**not active since 2017**](https://github.com/codefisher/toolbar_buttons).

#### 3.2. Another extension for closing all tabs

I tried, for example, these Firefox extensions for closing all tabs:

+ [**Close All Tabs**](https://addons.mozilla.org/ru/firefox/addon/close-all-tabs-webextension/?src=search)
+ [**Buttons**](https://addons.mozilla.org/ru/firefox/addon/close-all-button/?src=search)
+ [**Multi-Tab Close**](https://addons.mozilla.org/ru/firefox/addon/multitabx/?src=search)
+ [**Tab Closer**](https://addons.mozilla.org/ru/firefox/addon/tab-closer/?src=search)

But they don't close pinned tabs, what I need.

#### 3.3. Workplace managers

I tried Firefox extensions for workplace management/tabs grouping. Examples:

+ [**Simple Tab Groups**](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups)
+ [**Tabber**](https://addons.mozilla.org/en-US/firefox/addon/tabber)
+ [**Tabmarks**](https://addons.mozilla.org/en-US/firefox/addon/tabmarks)
+ [**Tab Group Switch**](https://addons.mozilla.org/ru/firefox/addon/tab-group-switch)

But use it, I can't get behavior, that I described on section 2 of this issue. In these extensions I can't prevent automatically adding new tabs to groups.

#### 3.4. Scripts

I can programmatically press shortcut in Firefox. Example AutoHotkey script:

```text
; [INFO] Activate Firefox window
WinActivate, ahk_exe firefox.exe
; [INFO] Press Win+Alt+W in activated window
Send +!w
```

But I can't find any method, how I can press to Firefox extension (“Close All Tabs Button”) button programmatically.

#### 4.1. “Firefox will close, if you close last tab”

It is [**possible**](https://superuser.com/a/1309894/572069) to prevent closing Firefox.

#### 4.2. “In your script you can click to button coordinates”

Yes, I can programmatically click to button of `Close All Tabs Button` extension, by calculating the exact `x` and `y` coordinates of this button. But:

1. I add/remove/disable Firefox extension → button coordinates will change → I will have to modify coordinates in my script every time.
1. Also, coordinates will change, if I resize Firefox window.

Clicking to specifying coordinates — is not the best idea for processes automation.

Thanks.

**Comment by Kristinita** [comment]
[**Additional details about the problem**](https://superuser.com/q/1537534/572069).

Thanks.

**Comment by mikecrittenden** [comment]
I think this is probably enough of an edge case that it doesn't need to be added to Shortkeys. I have only ever seen this one request for it. Most people I think prefer that pinned tabs stay pinned.
