### ISSUE TITLE
Firefox Shortcuts not working

### ISSUE THREAD

**Issue by lexluthor5** [mikecrittenden/shortkeys#323]
I have shortkeys working in chrome and I used to have it working in firefox a long time ago.  I've just come back to firefox and just nothing at all happens when I create shortcuts.  I've followed the guide here https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#None_of_my_shortcuts_are_working_Why_isnt_Shortkeys_doing_anything

Here's how it looks for alt-w that I set up.  I also have alt-z for previous tab and alt-x for next tab.

Any ideas?

![shortcut](https://user-images.githubusercontent.com/41312611/77791576-43bd0b00-703d-11ea-97d0-57224a9de70f.jpg)

**Comment by lexluthor5** [comment]
Anyone able to comment/assist with this?

**Comment by mikecrittenden** [comment]
Did you try any without alt? I'm wondering if alt is the problem.

**Comment by lexluthor5** [comment]
Wow, I'm an idiot, but you didn't notice it either :)  I had alt-w and it needs to be alt+w.

**Comment by mikecrittenden** [comment]
Oh great! Good catch!
