### ISSUE TITLE
Support action "Open the Find Bar to search the current page"

### ISSUE THREAD

**Issue by melissachang** [mikecrittenden/shortkeys#326]
I'm on a Mac laptop. I'm trying to use "Ctrl F" for "Find..." instead of "Command F". In Mac keyboard shortcuts, I mapped "Ctrl F" to "Find...". This works for most applications and most websites in Chrome. This doesn't work for Google Docs/Sheets; they don't use the standard Mac mappings.

I'm hoping to use this Chrome extension. There is a [Chrome shortcut for "Open the Find Bar to search the current page"](https://support.google.com/chrome/answer/157179?hl=en&ref_topic=25799). However, this [action is not supported by Shortkeys](https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys#full-list-of-commands).

**Comment by mikecrittenden** [comment]
I would love this as well but I've investigated it before and I can't find a way to trigger the built-in Find bar from an extension, unfortunately. If anyone finds a way, please do comment here and I will reopen.
