### ISSUE TITLE
It worked last week.... trying to suppress ctrl+enter in Yahoo Mail

### ISSUE THREAD

**Issue by jeffrey-friedl** [mikecrittenden/shortkeys#331]
Hi, I'm trying to suppress the ctrl+enter "send mail" feature of Yahoo Mail (https://mail.yahoo.com).   I thought I had it working last week with "ctrl+enter" set to "Do nothing", but it's not working now. For good measure, I tried various combos as well: 
<img width="722" alt="ScreenShot 2020-04-09 at 8 08 40 AM" src="https://user-images.githubusercontent.com/16525084/78841889-89b0a080-7a39-11ea-9556-af6f7413aa08.png">  
I've got muscle memory from other apps in which ctrl+enter means "start new paragraph", so I keep sending messages by accident. Doh! I'd appreciate your help.  Thanks!

**Comment by mikecrittenden** [comment]
Unfortunately if this is still an issue then there's not much Shortkeys can do it. Most likely, Yahoo is adding their key bindings after Shortkeys, so it's overriding Shortkeys' bindings.
