### ISSUE TITLE
some shortkeys not working win 10 chrome

### ISSUE THREAD

**Issue by kalamalka** [mikecrittenden/shortkeys#334]
some shortkeys not working - cant add new shortcuts with DEL or INS keys

using chrome build Version 81.0.4044.122 (Official Build) (64-bit) on WIndows 10 64 bit

**Comment by mikecrittenden** [comment]
If this is still an issue, can I see a screenshot of the settings page for a shortcut that isn't working for you?

**Comment by kalamalka** [comment]
Sorry to reply late. I wasnt able to get help right away and needed a fix. I decided to use AHK instead. Thanks
