### ISSUE TITLE
Shortkeys extensions, Cant disable key

### ISSUE THREAD

**Issue by GentleJens** [mikecrittenden/shortkeys#337]
Want to disable mouse button 4 and 5 hotkeys while using google chrome because i use it for push to talk. Whenever i try to hit mouse 5 in the shortkeys editor i get sent back to the previous page.

**Comment by mikecrittenden** [comment]
Unfortunately Shortkeys only deals with keyboard keys, not mouse buttons. Try https://chrome.google.com/webstore/detail/crxmouse-chrome-gestures/jlgkpaicikihijadgifklkbpdajbkhjo?hl=en for mouse buttons/gestures.
