### ISSUE TITLE
Feature request?

### ISSUE THREAD

**Issue by milkshakesandmutts** [mikecrittenden/shortkeys#341]
I bought this because I wanted it to type out phrases with shortcuts, but that doesn't seem to be a thing it does?

**Comment by mikecrittenden** [comment]
Sounds like maybe you're looking for something more like https://chrome.google.com/webstore/detail/auto-text-expander-for-go/iibninhmiggehlcdolcilmhacighjamp?hl=en ?

Sorry about that. Feel free to email me an order number (mikecrittenden@gmail.com) and I can refund you if Shortkeys isn't helpful for you.
