### ISSUE TITLE
shortcut changes being ignored

### ISSUE THREAD

**Issue by gamesturbator** [mikecrittenden/shortkeys#342]
ctrl+i brings up the bookmark sidebar. So I tried to change it to other behaviors, even disable browser shortcut, but it still opens the bookmark sidebar. Now I am on Windows10 and maybe that's overriding the behavior? IDK

BTW It would be nice to have an an option to "install extension from file" in the behavior pane, so I hope you add that. Thanks!

**Comment by mikecrittenden** [comment]
Is ctrl+i a built in browser shortcut? Or a custom one you have added? Are you in Chrome or FF?
