### ISSUE TITLE
Can't activate shortcut while on New Tab (or other Chrome) pages

### ISSUE THREAD

**Issue by ckrf** [mikecrittenden/shortkeys#343]
System: Chrome Version 81, Windows 10. 

When I am on a non-Web page, like chrome://new-tab-page or about:blank or chrome://bookmarks, Shortkeys shortcuts do **not** do anything. The shortcut extension icon is also gray instead of blue.

If this is the intended behavior, please consider this a feature request to change it. I got Shortkeys to create a shortcut to open a new tab with a page I use often. I have had to change my default new tab page to a website to be able to get this functionality, which introduces half a second of extra friction in every new tab I open and keeps me from using bookmarks as my new tab page.

**Comment by mikecrittenden** [comment]
Yeah, sadly this is a side effect of Chrome's extension API, which doesn't allow injecting key listeners to system pages.

That said, for some types of shortcuts, Shortkeys supports the built in Chrome "keyboard shortcuts" settings, which DOES listen on those pages. 

Here's some more info: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#Do_I_use_the_browsers_Keyboard_Shortcuts_settings_or_the_Shortkeys_options_page
