### ISSUE TITLE
Manual start required each time

### ISSUE THREAD

**Issue by spenovo** [mikecrittenden/shortkeys#344]
Hi, can anyone help with this problem?  I have the shortkeys set and saved but in order to get them working I have to go to addons and save them again every single time I open firefox.  Any ideas?  Thanks guys.

**Comment by mikecrittenden** [comment]
Do you by any chance have an extension or setting running that clears your browser storage every time you close the browser? I seem to remember another FF user having that problem.

**Comment by spenovo** [comment]
Hmmm possibly...

 

I'll investigate - thank you,

 

Spen

 
 

Sent: Monday, June 15, 2020 at 4:02 PM

**Comment by monkeylove** [comment]
> 
> 
> Do you by any chance have an extension or setting running that clears your browser storage every time you close the browser? I seem to remember another FF user having that problem.

Thanks for mentioning that. I have a similar problem and noted that I also use the Clear Browsing Data addon, and I set it to clear local storage as well. I'll remove that feature.
