### ISSUE TITLE
Open javascript/bookmarklet not working in FF77.0.1 ubuntu

### ISSUE THREAD

**Issue by SimonDedman** [mikecrittenden/shortkeys#348]
Hi folks, just seen the program and it's something I've been hoping for for a while. I have 2 javascript bookmarklets which I found online years ago that are super useful for going to sequentially numbered URLs, one higher and one lower respectively are:

`javascript:(function(){%20var%20e,s;%20IB=1;%20function%20isDigit(c)%20{%20return%20("0"%20<=%20c%20&&%20c%20<=%20"9")%20}%20L%20=%20location.href;%20LL%20=%20L.length;%20for%20(e=LL-1;%20e>=0;%20--e)%20if%20(isDigit(L.charAt(e)))%20{%20for(s=e-1;%20s>=0;%20--s)%20if%20(!isDigit(L.charAt(s)))%20break;%20break;%20}%20++s;%20if%20(e<0)%20return;%20oldNum%20=%20L.substring(s,e+1);%20newNum%20=%20""%20+%20(parseInt(oldNum,10)%20+%20IB);%20while%20(newNum.length%20<%20oldNum.length)%20newNum%20=%20"0"%20+%20newNum;%20location.href%20=%20L.substring(0,s)%20+%20newNum%20+%20L.slice(e+1);%20})();`

`javascript:(function(){%20var%20e,s;%20IB=-1;%20function%20isDigit(c)%20{%20return%20("0"%20<=%20c%20&&%20c%20<=%20"9")%20}%20L%20=%20location.href;%20LL%20=%20L.length;%20for%20(e=LL-1;%20e>=0;%20--e)%20if%20(isDigit(L.charAt(e)))%20{%20for(s=e-1;%20s>=0;%20--s)%20if%20(!isDigit(L.charAt(s)))%20break;%20break;%20}%20++s;%20if%20(e<0)%20return;%20oldNum%20=%20L.substring(s,e+1);%20newNum%20=%20""%20+%20(parseInt(oldNum,10)%20+%20IB);%20while%20(newNum.length%20<%20oldNum.length)%20newNum%20=%20"0"%20+%20newNum;%20location.href%20=%20L.substring(0,s)%20+%20newNum%20+%20L.slice(e+1);%20})();`

I've tried entering these as bookmark/bookmarklets current tab, and run javascript, with
`ctrl+.` / `ctrl+,`
`ctrl+'` / `ctrl+;`
`'` / `;`
None of which does anything. Am I doing something wrong or is this beyond the scope of the program due to API limitations etc?

Thanks!

**Comment by SimonDedman** [comment]
Oh, edit, I also tried ctrl+right/left, still nothing.

**Comment by mikecrittenden** [comment]
Have you tried just a simple JS one, like `alert('hi');` or something like that, to confirm that it's not the JS itself which is erroring? Any errors in the JS console?
