### ISSUE TITLE
Does the app include custom URL shortcuts too?

### ISSUE THREAD

**Issue by anth11** [mikecrittenden/shortkeys#349]

**Comment by mikecrittenden** [comment]
Do you mean, does it give you the ability to open a URL via a shortcut? If so, then yes.

**Comment by anth11** [comment]
I just purchased it to try opening a customer tab, for example, ctrl + q so that it can open Spotify in another tab but it didn't, even closed Chrome and reopened again and it still didn't work. 

And when I hovered on " Keyboard shortcut (Help)" on the main menu

I then clicked Help but it had nothing to show.

**Comment by anth11** [comment]
update: I started working after removing the spaces between ctrl + q 

However, it doesn't open automatically when I start the browser. It will only work once I have a tab that is actively open.

**Comment by mikecrittenden** [comment]
Yeah sadly those types of shortcuts don't work on "system pages" such as the new tab page, or the browser settings page, etc. Here's some more info: https://github.com/mikecrittenden/shortkeys/wiki/FAQs-and-Troubleshooting#None_of_my_shortcuts_are_working_Why_isnt_Shortkeys_doing_anything

**Comment by anth11** [comment]
My feedback after looking for my second URL to use is: please add a search function, or at least a scroll bar to the right?

It's taking forever to find the specific link.

Or could be that I can also just paste the link, rather having to go look for it?

**Comment by samdutton** [comment]
OK — this is embarrassing, but I can't work out how to set a shortcut to open a URL.

For example, if I want to set ctrl+g to open github.com, how do I do it? I've looked through the documentation, but can't find anything. 

Likewise, I can see how to specify a shortcut to 'Run JavaScript' — but where do I specify the JavaScript to run?

![image](https://user-images.githubusercontent.com/205226/140933898-70de2aaa-8820-4636-bef2-c499b3ca8e79.png)

Apologies if I'm missing something obvious...

**Comment by mikecrittenden** [comment]
@samdutton sorry, the UI is terrible there - you click the little arrow icon on the far left of your screenshot to expand the options.

**Comment by samdutton** [comment]
Ah! Thanks @mikecrittenden .
