### ISSUE TITLE
Can't download the extension when using Brave

### ISSUE THREAD

**Issue by JohanRJ** [mikecrittenden/shortkeys#353]
Hi everyone. 

I can't seem to download the extension when using Brave. Works fine using Chrome. 

When trying to download i get a 'missing permission' error message. 
Can anyone help me here?

**Comment by mikecrittenden** [comment]
Yeah, unfortunately Brave doesn't support paid Chrome extensions yet. For Brave, your best bet is to manually install from the releases page: https://github.com/mikecrittenden/shortkeys/releases
