### ISSUE TITLE
Disabling Ctrl-A (Select All) everywhere

### ISSUE THREAD

**Issue by jefferysmall** [mikecrittenden/shortkeys#354]
With my UNIX-style keyboard, I constantly accidentally hit Ctrl-A and select everything.  I wish to disable this built-in shortcut in Firefox.  On the Shortkeys Preference page I have assigned "Ctrl-a" to "Do nothing" and checked "Activate while in form fields."  I have Saved this assignment and then reloaded various pages and tested it.  Ctrl-A continues to select all both within or outside of a form.

Any idea as to what I'm doing wrong?

Xubuntu 19.10
Firefox 77.0.1
Shortkeys 3.0.4

**Comment by mikecrittenden** [comment]
Yeah, unfortunately that's not something that an extension has the power to override. A shortcut like that is baked in at such a deep level that you'd probably have to look into OS-level keyboard mapping utilities to change it.

**Comment by jefferysmall** [comment]
Thanks Mike!
