### ISSUE TITLE
"Help" link seems broken

### ISSUE THREAD

**Issue by d73** [mikecrittenden/shortkeys#372]
Latest version that I just downloaded from Github a few min ago
I am running Brave, also latest version
Attempting to add a new keyboard shortcut, and clicking either of the "Help" hyperlinks
https://i.imgur.com/0Sw01yA.png

Get the sad broken image on the browser
https://i.imgur.com/woFy1ZG.png

Minor issue, since I can go to the help page directly, assuming this is the one
https://github.com/mikecrittenden/shortkeys/wiki/How-To-Use-Shortkeys

Thank you :)

**Comment by mikecrittenden** [comment]
Fixed in the latest version. Thanks!
