### ISSUE TITLE
Claiming firefox as Chrome when using Firefox

### ISSUE THREAD

**Issue by revi** [mikecrittenden/shortkeys#373]
![image](https://user-images.githubusercontent.com/7630875/94295337-0c9fc600-ff9c-11ea-9cac-bb1c78912e6b.png)

Browser using Firefox but it claims to be Chrome.

(Sorry, clicked enter too early)

**Comment by revi** [comment]
Firefox version: 81.0 (Windows 64-bit)
Extension version: 3.0.4

**Comment by mikecrittenden** [comment]
This is fixed in the latest version and will be included in the next FF release. Thanks!
