### ISSUE TITLE
Doesn't work in this site

### ISSUE THREAD

**Issue by ttodua** [mikecrittenden/shortkeys#376]
On specific areas of site, it doesn't work. For example:

1) set any Javascript-code to run on clicking `ctrl+f` (or `ctrl+h`)
2) Go to: https://www.tradingview.com/chart/
3) Open up the "Pine Editor" - > https://i.imgur.com/mUDJPue.png
4) click somewhere inside the "editor textarea" and click i.e.  `ctrl+f`. The extension will not work, because probably the textarea overrides it. How can we make extension to work in such cases too?

**Comment by mikecrittenden** [comment]
Yeah, that's tricky. If there are websites already listening for shortcuts you have defined in Shortkeys, there's not much we can do. My only advice is to try to stick to key bindings that are unlikely to be used elsewhere. 

That said, note that you can choose to whitelist/blacklist websites when editing shortcuts in the Shortkeys config.
