### ISSUE TITLE
Utilize Shortkeys to simply type in repetitive text?

### ISSUE THREAD

**Issue by HughKallen** [mikecrittenden/shortkeys#377]
As an admin, I have to append the same text/link into a post in a facebook group over and over.  I would like to be able to utilize shortkeys to type this in for me.

It might even be possible already, by using the run javascript command, but I don't program to know how to create the correct javascript code.

Help?

**Comment by mdallaswatson** [comment]
check out autohotkey

**Comment by mikecrittenden** [comment]
Agreed with previous comment - there are better tools for this already, such as autohotkey.

**Comment by tomhundt** [comment]
1. AHK is a Windows app.  Some of us aren't using Windows.
1. More important: AHK can't tell what website you're on.  So, your shortcut to type a bunch of boilerplate on facebook.com is also going to do the same thing on twitter.com.  Not helpful!
