### ISSUE TITLE
[BUG] New UI is not showing the labels

### ISSUE THREAD

**Issue by user8446** [mikecrittenden/shortkeys#378]
After the latest update, the new UI is either not showing the labels or has cleared them

**Comment by mikecrittenden** [comment]
Hmmmmm...that's odd. Are you still able to add new labels and save them successfully?

**Comment by user8446** [comment]
Yes I can add them back and it is saving. I just wanted you to be aware if this was something you can catch sooner than later before everyone is updated.

**Comment by mikecrittenden** [comment]
Thank you! Investigating now...
