### ISSUE TITLE
Add screenshot behavior(s)?

### ISSUE THREAD

**Issue by jakimfett** [mikecrittenden/shortkeys#379]
(feature request, I guess?)

In my search for a painless screenshot process, I ran across your browser plugin.
Unfortunately, I don't see a way to trigger screenshots as a behaviour in the "New keyboard shortcut" drop-down.

Would it be possible to add both "take current viewport screenshot" and "take whole page screenshot" behaviours, somehow?
These are both available via the "take screenshot" functionality inside Firefox, but you have to [toggle a checkbox](https://support.mozilla.org/en-US/questions/1117336#answer-863896) to swap between the outcomes in the vanilla UI.

Does this seem feasible?

**Comment by pikou1995** [comment]
Hey, I'm working on it. I would glad to say it will coming soon!😄

**Comment by mikecrittenden** [comment]
Merged #403 to fix this. Thanks @pikou1995!
