### ISSUE TITLE
missing 90deg rotation behaviour

### ISSUE THREAD

**Issue by nirharpaz** [mikecrittenden/shortkeys#380]

**Comment by mikecrittenden** [comment]
I'm not sure what this means. Rotate what?

**Comment by nirharpaz** [comment]
hi
I may have been inaccurate, rotating the page 90deg (mostly useful when ir
comes to images and videos but in other scenarios as well).

**Comment by mikecrittenden** [comment]
Gotcha. That is an interesting idea, but I think it's not going to be commonly used enough to add it to Shortkeys. Thanks for the suggestion!
