### ISSUE TITLE
cttrl+w still closes tabs on chrome

### ISSUE THREAD

**Issue by gulfpearl** [mikecrittenden/shortkeys#381]
I got this extension to disable chrome closing tabs with ctrl+w, however after configuring it, nothing has changed and it still closes my tabs. I paid for this in the store btw. 

Here is the generated conf:

[
  {
    "key": "ctrl+w",
    "label": "CW",
    "action": "disable",
    "sites": "",
    "sitesArray": [
      ""
    ],
    "activeInInputs": true,
    "blacklist": false
  },
  {
    "sites": "",
    "sitesArray": [
      ""
    ]
  }
]

**Comment by mikecrittenden** [comment]
Try going to chrome://extensions/shortcuts and adding it there, like so:

![image](https://user-images.githubusercontent.com/32261/98034753-7efa9600-1de5-11eb-8787-c77188883a4b.png)

That works on my end so I'm closing this, but holler if it doesn't work for you.

**Comment by jabcreations** [comment]
> Try going to chrome://extensions/shortcuts and adding it there, like so:
> 
> ![image](https://user-images.githubusercontent.com/32261/98034753-7efa9600-1de5-11eb-8787-c77188883a4b.png)
> 
> That works on my end so I'm closing this, but holler if it doesn't work for you.

Are you literally typing the ^ (6 key) or is that generated by pressing the keys? I've really figuring out how to get around the interface (using Waterfox Current) though no matter what I do Control + W just won't die.
