### ISSUE TITLE
Version conflict

### ISSUE THREAD

**Issue by dhbmarcos** [mikecrittenden/shortkeys#383]
In file package-lock.json (https://github.com/mikecrittenden/shortkeys/blob/62adcc45f265c55961c46fed396887b2483c680b/package.json#L3) and package.json and (https://github.com/mikecrittenden/shortkeys/blob/62adcc45f265c55961c46fed396887b2483c680b/package-lock.json#L3), the **version** property is `3.0.7` in tag v4.0.2.

**Comment by mikecrittenden** [comment]
Fixed in commit 3776a4e. Thanks!
