### ISSUE TITLE
Option to backup/restore settings needs "Select all" checkbox

### ISSUE THREAD

**Issue by risk00** [mikecrittenden/shortkeys#40]
This would be helpful not only for backup purposes but to transfer settings to another computer.

**Comment by mikecrittenden** [comment]
Update here: there's a pull request ready for anyone who's brave enough to review it here https://github.com/mikecrittenden/chrome-shortkeys/pull/101. Feedback welcome! If I don't get any then I'll go ahead and merge it in the next couple days. Here are some screenshots:

![import](https://user-images.githubusercontent.com/32261/33510659-ac8e5bfe-d6dc-11e7-832e-94ebae00efd0.png)

![export](https://user-images.githubusercontent.com/32261/33510660-aee22f16-d6dc-11e7-8b83-19c49434702a.png)

**Comment by mikecrittenden** [comment]
Went ahead and merged - I tested thoroughly and it seems solid to me.

**Comment by mikecrittenden** [comment]
This has been published to the webstore now as well - version 2.2.1. Let me know what you all think if/when you try it out! See previous comments for screenshots.

cc @fhightower @risk00 @a-diagonal

**Comment by darkzbaron** [comment]
Any chance to add a "select all", I have got about 50 shortcuts and I have to select them all manually which is not convenient. Otherwise, great work! Thanks!

**Comment by a-diagonal** [comment]
Amazing reaction... great work... thanks for that.... love you long time...

**Comment by mikecrittenden** [comment]
DUH, how did I miss "select all"? I'll reopen this ticket to add that.

**Comment by darkzbaron** [comment]
also, I am trying to find where the settings are store locally (Windows System) so that I can have a script to sync the file to my dropbox. Any help? Thanks again!!

**Comment by mikecrittenden** [comment]
@darkzbaron hmm - try this: https://superuser.com/questions/507536/where-does-google-chrome-save-localstorage-from-extensions

**Comment by mikecrittenden** [comment]
Pushed a fix to add "Select all" which will be included in the next release.

**Comment by fhightower** [comment]
Thanks @mikecrittenden ! This is great!!!
