### ISSUE TITLE
Want to use single key as shortcut.

### ISSUE THREAD

**Issue by Frogger-01** [mikecrittenden/shortkeys#417]
I am on an Intel Mac (Big Sur) and running latest version of Firefox (88). I wanted to create a shortcut to go Back and Forward in my browser history. I want to use the back arrow key to go back and the forward arrow key to go forward, no modifiers. The new shortcut window will not let me type in either of those keys. It directed me to look at this first:

"To try it, go back to the extensions page, click the menu icon at the top left, then click "Keyboard Shortcuts". You can still add it here as well." 

However, there is no menu icon there. I'm am not savvy in any programming at all, so simpleton answer please. The instructions said you could use the back and forward buttons for shortcuts and you could use zero modifiers. Am I reading that wrong, or is it just not doing what it is supposed to?

**Comment by srikat** [comment]
Just tested these settings on Firefox and they work fine here.

<img width="1058" alt="CleanShot 2021-04-24 at 19 13 55@2x" src="https://user-images.githubusercontent.com/2188656/115953865-500de300-a531-11eb-824d-cd996770f4da.png">

You have to literally type `left` in the first input and similarly, `right` for the going forward shortcut.

**Comment by Frogger-01** [comment]
Works like a charm! Thanks so much for your help srikat! So simple, yet I never would have thought of that.
