### ISSUE TITLE
Cycling / switching between tabs doesn't work (next tab and previous tab) 

### ISSUE THREAD

**Issue by mithi-aeronology** [mikecrittenden/shortkeys#422]
When I change the shortcut for `next tab` and `previous tab`  on mac.
it only moves between the first and second tab.  It doesn't go to the third tab and so on. 
Is this the expected behavior?

How to I create a shortcut similar to the behavior fo the default short cut `Ctrl + Shift + Tab`

Thanks! :)

**Comment by KvalheimRacing** [comment]
How did you fix this? The functions for `next tab` and `previous tab` does not behave like the standard `ctrl+tab` and `ctrl+shift+tab`

**Comment by KvalheimRacing** [comment]
How did you fix this? The functions for `next tab` and `previous tab` does not behave like the standard `ctrl+tab` and `ctrl+shift+tab`
