### ISSUE TITLE
No option to insert Javascript code

### ISSUE THREAD

**Issue by Jeriooo** [mikecrittenden/shortkeys#445]
When adding a new shortcut and selecting the 'run javascript' tab, I am not provided with any option to specify/insert said javascript code:

![image](https://user-images.githubusercontent.com/83526614/127743214-e7c6d1f2-79bf-461f-8a17-f35eefc2de4e.png)

**Comment by yramchandani** [comment]
+1, also experiencing this

**Comment by mikecrittenden** [comment]
Clicking the little arrow on the right side should expand it. Can you confirm?

**Comment by TheCodingKerbal** [comment]
> Clicking the little arrow on the left side should expand it. Can you confirm?

![image](https://user-images.githubusercontent.com/85450055/128656427-76312a6c-0b18-414e-afff-ebeedb29e2d2.png)
It does work.
